import type {
  WeatherDataType,
  RawCurrentWeatherDataType,
  RawDayWeatherDataType,
  DayWeatherDataType,
  WeatherIconType,
} from './weatherTypes'
import { currentWeatherData } from '../stores/store'
import { getSunriseSunset } from './time'
const ENDPOINT = 'https://api.brightsky.dev/'
let currentWeatherUrl = new URL(ENDPOINT + 'current_weather')
let weatherUrl = new URL(ENDPOINT + 'weather')

export default class Weather {
  static async getCurrentWeather(lat: number, lon: number) {
    currentWeatherUrl.search = new URLSearchParams({
      lat: lat.toString(),
      lon: lon.toString(),
      tz: 'Europe/Berlin',
    }).toString()
    const result = this.processCurrentWeatherData(
      await (await fetch(currentWeatherUrl.toString())).json()
    )

    currentWeatherData.set(result)
    return result
  }

  static async getWeather(lat: number, lon: number, days: 3) {}

  static getCurrentWeatherDummy() {
    const tempCurrentWeatherData = {
      weather: {
        source_id: 18377,
        timestamp: new Date(Date.now()).toISOString(),
        cloud_cover: 100,
        condition: 'rain',
        dew_point: 3.28,
        precipitation_10: 0.1,
        precipitation_30: 0.3,
        precipitation_60: 0.6,
        pressure_msl: 1017.4,
        relative_humidity: 87,
        visibility: 9600,
        wind_direction_10: 90,
        wind_direction_30: 293,
        wind_direction_60: 293,
        wind_speed_10: 18.4,
        wind_speed_30: 18.7,
        wind_speed_60: 17.6,
        wind_gust_direction_10: 290,
        wind_gust_direction_30: 290,
        wind_gust_direction_60: 290,
        wind_gust_speed_10: 32.0,
        wind_gust_speed_30: 34.2,
        wind_gust_speed_60: 34.6,
        sunshine_30: 0.0,
        sunshine_60: 0.0,
        temperature: 5.2,
        fallback_source_ids: {},
        icon: 'rain',
      },
      sources: [],
    } as RawCurrentWeatherDataType

    return this.processCurrentWeatherData(tempCurrentWeatherData)
  }

  static getWeatherDummy() {
    const tempWeatherData = {
      weather: [
        {
          timestamp: '2021-05-25T00:00:00+02:00',
          source_id: 4089,
          precipitation: 0.7,
          pressure_msl: 1015.9,
          sunshine: 0.0,
          temperature: 9.9,
          wind_direction: 233,
          wind_speed: 11.1,
          cloud_cover: 100,
          dew_point: 8.3,
          relative_humidity: null,
          visibility: 32700,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-05-25T01:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1016.2,
          sunshine: 0.0,
          temperature: 9.7,
          wind_direction: 232,
          wind_speed: 11.1,
          cloud_cover: 100,
          dew_point: 8.3,
          relative_humidity: null,
          visibility: 34200,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-05-25T02:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1016.4,
          sunshine: 0.0,
          temperature: 9.3,
          wind_direction: 236,
          wind_speed: 11.1,
          cloud_cover: 100,
          dew_point: 7.9,
          relative_humidity: null,
          visibility: 34800,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-05-25T03:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1016.9,
          sunshine: 0.0,
          temperature: 9.1,
          wind_direction: 235,
          wind_speed: 11.1,
          cloud_cover: 100,
          dew_point: 7.5,
          relative_humidity: null,
          visibility: 36200,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-25T04:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1017.2,
          sunshine: 0.0,
          temperature: 9.1,
          wind_direction: 237,
          wind_speed: 13.0,
          cloud_cover: 100,
          dew_point: 6.9,
          relative_humidity: null,
          visibility: 41600,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-25T05:00:00+02:00',
          source_id: 4089,
          precipitation: 0.2,
          pressure_msl: 1017.4,
          sunshine: 0.0,
          temperature: 8.6,
          wind_direction: 236,
          wind_speed: 13.0,
          cloud_cover: 100,
          dew_point: 6.3,
          relative_humidity: null,
          visibility: 50800,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-25T06:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1017.9,
          sunshine: 0.0,
          temperature: 8.6,
          wind_direction: 238,
          wind_speed: 13.0,
          cloud_cover: 100,
          dew_point: 6.0,
          relative_humidity: null,
          visibility: 52700,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-25T07:00:00+02:00',
          source_id: 4089,
          precipitation: 0.2,
          pressure_msl: 1018.4,
          sunshine: 0.0,
          temperature: 8.4,
          wind_direction: 240,
          wind_speed: 13.0,
          cloud_cover: 100,
          dew_point: 5.4,
          relative_humidity: null,
          visibility: 56300,
          wind_gust_direction: null,
          wind_gust_speed: 29.6,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-25T08:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1018.8,
          sunshine: 0.0,
          temperature: 8.2,
          wind_direction: 240,
          wind_speed: 14.8,
          cloud_cover: 99,
          dew_point: 5.0,
          relative_humidity: null,
          visibility: 57900,
          wind_gust_direction: null,
          wind_gust_speed: 29.6,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-25T09:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1019.4,
          sunshine: 0.0,
          temperature: 8.7,
          wind_direction: 245,
          wind_speed: 14.8,
          cloud_cover: 99,
          dew_point: 4.8,
          relative_humidity: null,
          visibility: 58800,
          wind_gust_direction: null,
          wind_gust_speed: 31.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-25T10:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1019.7,
          sunshine: 0.0,
          temperature: 9.2,
          wind_direction: 246,
          wind_speed: 16.7,
          cloud_cover: 100,
          dew_point: 4.4,
          relative_humidity: null,
          visibility: 57100,
          wind_gust_direction: null,
          wind_gust_speed: 33.3,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-25T11:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1019.9,
          sunshine: 0.0,
          temperature: 9.7,
          wind_direction: 247,
          wind_speed: 16.7,
          cloud_cover: 99,
          dew_point: 4.0,
          relative_humidity: null,
          visibility: 56200,
          wind_gust_direction: null,
          wind_gust_speed: 37.0,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-25T12:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1019.7,
          sunshine: 5.0,
          temperature: 10.6,
          wind_direction: 251,
          wind_speed: 18.5,
          cloud_cover: 96,
          dew_point: 3.5,
          relative_humidity: null,
          visibility: 58900,
          wind_gust_direction: null,
          wind_gust_speed: 38.9,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-25T13:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1019.5,
          sunshine: 9.0,
          temperature: 11.2,
          wind_direction: 252,
          wind_speed: 20.4,
          cloud_cover: 90,
          dew_point: 3.2,
          relative_humidity: null,
          visibility: 66900,
          wind_gust_direction: null,
          wind_gust_speed: 40.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-25T14:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1019.4,
          sunshine: 16.0,
          temperature: 11.9,
          wind_direction: 255,
          wind_speed: 22.2,
          cloud_cover: 81,
          dew_point: 2.8,
          relative_humidity: null,
          visibility: 73900,
          wind_gust_direction: null,
          wind_gust_speed: 42.6,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-25T15:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1019.3,
          sunshine: 20.0,
          temperature: 12.4,
          wind_direction: 256,
          wind_speed: 22.2,
          cloud_cover: 75,
          dew_point: 2.4,
          relative_humidity: null,
          visibility: 85600,
          wind_gust_direction: null,
          wind_gust_speed: 44.5,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-25T16:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1019.1,
          sunshine: 27.0,
          temperature: 12.8,
          wind_direction: 263,
          wind_speed: 22.2,
          cloud_cover: 68,
          dew_point: 2.2,
          relative_humidity: null,
          visibility: 85200,
          wind_gust_direction: null,
          wind_gust_speed: 46.3,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-25T17:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1018.9,
          sunshine: 31.0,
          temperature: 13.1,
          wind_direction: 262,
          wind_speed: 20.4,
          cloud_cover: 63,
          dew_point: 1.9,
          relative_humidity: null,
          visibility: 93700,
          wind_gust_direction: null,
          wind_gust_speed: 44.5,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-25T18:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1019.1,
          sunshine: 34.0,
          temperature: 12.7,
          wind_direction: 263,
          wind_speed: 20.4,
          cloud_cover: 59,
          dew_point: 2.0,
          relative_humidity: null,
          visibility: 90000,
          wind_gust_direction: null,
          wind_gust_speed: 44.5,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-25T19:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1019.3,
          sunshine: 35.0,
          temperature: 12.7,
          wind_direction: 264,
          wind_speed: 16.7,
          cloud_cover: 56,
          dew_point: 2.3,
          relative_humidity: null,
          visibility: 90000,
          wind_gust_direction: null,
          wind_gust_speed: 40.8,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-25T20:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1019.6,
          sunshine: 29.0,
          temperature: 12.1,
          wind_direction: 261,
          wind_speed: 14.8,
          cloud_cover: 53,
          dew_point: 2.3,
          relative_humidity: null,
          visibility: 90000,
          wind_gust_direction: null,
          wind_gust_speed: 33.3,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-25T21:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1020.2,
          sunshine: 19.0,
          temperature: 11.3,
          wind_direction: 249,
          wind_speed: 11.1,
          cloud_cover: 53,
          dew_point: 2.6,
          relative_humidity: null,
          visibility: 90000,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-05-25T22:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1020.8,
          sunshine: 0.0,
          temperature: 10.4,
          wind_direction: 228,
          wind_speed: 9.3,
          cloud_cover: 54,
          dew_point: 2.9,
          relative_humidity: null,
          visibility: 93700,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-05-25T23:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1021.2,
          sunshine: 0.0,
          temperature: 9.8,
          wind_direction: 218,
          wind_speed: 9.3,
          cloud_cover: 63,
          dew_point: 3.2,
          relative_humidity: null,
          visibility: 90000,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-05-26T00:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1021.6,
          sunshine: 0.0,
          temperature: 9.4,
          wind_direction: 218,
          wind_speed: 9.3,
          cloud_cover: 68,
          dew_point: 3.3,
          relative_humidity: null,
          visibility: 92200,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-05-26T01:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1021.4,
          sunshine: 0.0,
          temperature: 9.1,
          wind_direction: 221,
          wind_speed: 9.3,
          cloud_cover: 79,
          dew_point: 3.4,
          relative_humidity: null,
          visibility: 88900,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-05-26T02:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1021.2,
          sunshine: 0.0,
          temperature: 9.1,
          wind_direction: 219,
          wind_speed: 11.1,
          cloud_cover: 93,
          dew_point: 3.5,
          relative_humidity: null,
          visibility: 87300,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T03:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1020.9,
          sunshine: 0.0,
          temperature: 8.9,
          wind_direction: 217,
          wind_speed: 11.1,
          cloud_cover: 94,
          dew_point: 3.6,
          relative_humidity: null,
          visibility: 81400,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T04:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1020.7,
          sunshine: 0.0,
          temperature: 8.8,
          wind_direction: 213,
          wind_speed: 11.1,
          cloud_cover: 95,
          dew_point: 3.6,
          relative_humidity: null,
          visibility: 81600,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T05:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1020.3,
          sunshine: 0.0,
          temperature: 8.9,
          wind_direction: 212,
          wind_speed: 9.3,
          cloud_cover: 91,
          dew_point: 3.8,
          relative_humidity: null,
          visibility: 90400,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T06:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1020.1,
          sunshine: 4.0,
          temperature: 9.1,
          wind_direction: 211,
          wind_speed: 9.3,
          cloud_cover: 92,
          dew_point: 3.9,
          relative_humidity: null,
          visibility: 87000,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T07:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1019.8,
          sunshine: 7.0,
          temperature: 9.6,
          wind_direction: 207,
          wind_speed: 9.3,
          cloud_cover: 91,
          dew_point: 4.1,
          relative_humidity: null,
          visibility: 85500,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T08:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1019.6,
          sunshine: 12.0,
          temperature: 10.7,
          wind_direction: 218,
          wind_speed: 11.1,
          cloud_cover: 90,
          dew_point: 4.1,
          relative_humidity: null,
          visibility: 74700,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T09:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1019.2,
          sunshine: 16.0,
          temperature: 11.8,
          wind_direction: 225,
          wind_speed: 13.0,
          cloud_cover: 87,
          dew_point: 4.1,
          relative_humidity: null,
          visibility: 70900,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T10:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1018.7,
          sunshine: 17.0,
          temperature: 12.8,
          wind_direction: 236,
          wind_speed: 13.0,
          cloud_cover: 85,
          dew_point: 4.1,
          relative_humidity: null,
          visibility: 65900,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T11:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1018.1,
          sunshine: 19.0,
          temperature: 13.3,
          wind_direction: 239,
          wind_speed: 13.0,
          cloud_cover: 84,
          dew_point: 4.1,
          relative_humidity: null,
          visibility: 66800,
          wind_gust_direction: null,
          wind_gust_speed: 29.6,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T12:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.4,
          sunshine: 18.0,
          temperature: 13.9,
          wind_direction: 243,
          wind_speed: 14.8,
          cloud_cover: 85,
          dew_point: 4.0,
          relative_humidity: null,
          visibility: 62800,
          wind_gust_direction: null,
          wind_gust_speed: 29.6,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T13:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.9,
          sunshine: 18.0,
          temperature: 14.1,
          wind_direction: 244,
          wind_speed: 14.8,
          cloud_cover: 87,
          dew_point: 4.1,
          relative_humidity: null,
          visibility: 65400,
          wind_gust_direction: null,
          wind_gust_speed: 31.5,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T14:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.1,
          sunshine: 15.0,
          temperature: 14.3,
          wind_direction: 252,
          wind_speed: 14.8,
          cloud_cover: 93,
          dew_point: 4.5,
          relative_humidity: null,
          visibility: 66800,
          wind_gust_direction: null,
          wind_gust_speed: 31.5,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T15:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.2,
          sunshine: 12.0,
          temperature: 14.1,
          wind_direction: 254,
          wind_speed: 14.8,
          cloud_cover: 93,
          dew_point: 4.8,
          relative_humidity: null,
          visibility: 62300,
          wind_gust_direction: null,
          wind_gust_speed: 31.5,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T16:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.3,
          sunshine: 10.0,
          temperature: 14.1,
          wind_direction: 254,
          wind_speed: 14.8,
          cloud_cover: 94,
          dew_point: 5.2,
          relative_humidity: null,
          visibility: 64600,
          wind_gust_direction: null,
          wind_gust_speed: 29.6,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T17:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1016.4,
          sunshine: 7.0,
          temperature: 13.5,
          wind_direction: 256,
          wind_speed: 14.8,
          cloud_cover: 96,
          dew_point: 5.8,
          relative_humidity: null,
          visibility: 63500,
          wind_gust_direction: null,
          wind_gust_speed: 31.5,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-05-26T18:00:00+02:00',
          source_id: 4089,
          precipitation: 0.2,
          pressure_msl: 1017.1,
          sunshine: 7.0,
          temperature: 13.1,
          wind_direction: 258,
          wind_speed: 13.0,
          cloud_cover: 95,
          dew_point: 6.2,
          relative_humidity: null,
          visibility: 58300,
          wind_gust_direction: null,
          wind_gust_speed: 29.6,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T19:00:00+02:00',
          source_id: 4089,
          precipitation: 0.2,
          pressure_msl: 1017.4,
          sunshine: 6.0,
          temperature: 12.9,
          wind_direction: 254,
          wind_speed: 11.1,
          cloud_cover: 94,
          dew_point: 6.5,
          relative_humidity: null,
          visibility: 62300,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T20:00:00+02:00',
          source_id: 4089,
          precipitation: 0.2,
          pressure_msl: 1017.8,
          sunshine: 5.0,
          temperature: 12.2,
          wind_direction: 249,
          wind_speed: 11.1,
          cloud_cover: 93,
          dew_point: 6.9,
          relative_humidity: null,
          visibility: 61000,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T21:00:00+02:00',
          source_id: 4089,
          precipitation: 0.2,
          pressure_msl: 1018.4,
          sunshine: 3.0,
          temperature: 11.6,
          wind_direction: 241,
          wind_speed: 9.3,
          cloud_cover: 91,
          dew_point: 7.1,
          relative_humidity: null,
          visibility: 56800,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T22:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1018.9,
          sunshine: 1.0,
          temperature: 11.2,
          wind_direction: 231,
          wind_speed: 9.3,
          cloud_cover: 89,
          dew_point: 7.3,
          relative_humidity: null,
          visibility: 55300,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-26T23:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1019.2,
          sunshine: 0.0,
          temperature: 10.8,
          wind_direction: 223,
          wind_speed: 9.3,
          cloud_cover: 88,
          dew_point: 7.6,
          relative_humidity: null,
          visibility: 53500,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T00:00:00+02:00',
          source_id: 4089,
          precipitation: 0.2,
          pressure_msl: 1019.3,
          sunshine: 0.0,
          temperature: 10.4,
          wind_direction: 221,
          wind_speed: 9.3,
          cloud_cover: 89,
          dew_point: 7.7,
          relative_humidity: null,
          visibility: 48700,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T01:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1019.4,
          sunshine: 0.0,
          temperature: 10.5,
          wind_direction: 218,
          wind_speed: 9.3,
          cloud_cover: 90,
          dew_point: 8.1,
          relative_humidity: null,
          visibility: 50500,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T02:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1019.3,
          sunshine: 0.0,
          temperature: 10.5,
          wind_direction: 215,
          wind_speed: 9.3,
          cloud_cover: 92,
          dew_point: 7.9,
          relative_humidity: null,
          visibility: 48600,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T03:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1019.1,
          sunshine: 0.0,
          temperature: 10.2,
          wind_direction: 218,
          wind_speed: 9.3,
          cloud_cover: 94,
          dew_point: 7.9,
          relative_humidity: null,
          visibility: 44900,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T04:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1018.9,
          sunshine: 0.0,
          temperature: 10.1,
          wind_direction: 217,
          wind_speed: 9.3,
          cloud_cover: 96,
          dew_point: 8.0,
          relative_humidity: null,
          visibility: 42800,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T05:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1018.6,
          sunshine: 0.0,
          temperature: 10.1,
          wind_direction: 218,
          wind_speed: 9.3,
          cloud_cover: 98,
          dew_point: 7.9,
          relative_humidity: null,
          visibility: 40800,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T06:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1018.5,
          sunshine: 3.0,
          temperature: 10.3,
          wind_direction: 218,
          wind_speed: 9.3,
          cloud_cover: 96,
          dew_point: 7.9,
          relative_humidity: null,
          visibility: 38400,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T07:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1018.5,
          sunshine: 3.0,
          temperature: 10.8,
          wind_direction: 218,
          wind_speed: 9.3,
          cloud_cover: 93,
          dew_point: 8.1,
          relative_humidity: null,
          visibility: 40400,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T08:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1018.4,
          sunshine: 7.0,
          temperature: 11.5,
          wind_direction: 222,
          wind_speed: 9.3,
          cloud_cover: 89,
          dew_point: 8.3,
          relative_humidity: null,
          visibility: 39600,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T09:00:00+02:00',
          source_id: 4089,
          precipitation: 0.2,
          pressure_msl: 1018.5,
          sunshine: 11.0,
          temperature: 12.2,
          wind_direction: 237,
          wind_speed: 11.1,
          cloud_cover: 90,
          dew_point: 8.3,
          relative_humidity: null,
          visibility: 39100,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T10:00:00+02:00',
          source_id: 4089,
          precipitation: 0.2,
          pressure_msl: 1018.3,
          sunshine: 10.0,
          temperature: 12.7,
          wind_direction: 247,
          wind_speed: 11.1,
          cloud_cover: 91,
          dew_point: 8.3,
          relative_humidity: null,
          visibility: 38600,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T11:00:00+02:00',
          source_id: 4089,
          precipitation: 0.2,
          pressure_msl: 1018.5,
          sunshine: 12.0,
          temperature: 13.0,
          wind_direction: 256,
          wind_speed: 13.0,
          cloud_cover: 97,
          dew_point: 8.2,
          relative_humidity: null,
          visibility: 32600,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T12:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1018.6,
          sunshine: 12.0,
          temperature: 13.4,
          wind_direction: 265,
          wind_speed: 13.0,
          cloud_cover: 96,
          dew_point: 8.2,
          relative_humidity: null,
          visibility: 36500,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T13:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1018.7,
          sunshine: 9.0,
          temperature: 13.5,
          wind_direction: 270,
          wind_speed: 13.0,
          cloud_cover: 98,
          dew_point: 8.2,
          relative_humidity: null,
          visibility: 36700,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T14:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1018.4,
          sunshine: 10.0,
          temperature: 13.4,
          wind_direction: 273,
          wind_speed: 13.0,
          cloud_cover: 99,
          dew_point: 8.3,
          relative_humidity: null,
          visibility: 40600,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T15:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1018.4,
          sunshine: 9.0,
          temperature: 13.3,
          wind_direction: 276,
          wind_speed: 13.0,
          cloud_cover: 97,
          dew_point: 8.1,
          relative_humidity: null,
          visibility: 39600,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T16:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1018.7,
          sunshine: 11.0,
          temperature: 13.1,
          wind_direction: 276,
          wind_speed: 13.0,
          cloud_cover: 95,
          dew_point: 8.1,
          relative_humidity: null,
          visibility: 40200,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T17:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1018.9,
          sunshine: 12.0,
          temperature: 13.1,
          wind_direction: 276,
          wind_speed: 11.1,
          cloud_cover: 93,
          dew_point: 8.0,
          relative_humidity: null,
          visibility: 41700,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T18:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1019.3,
          sunshine: 12.0,
          temperature: 12.7,
          wind_direction: 278,
          wind_speed: 11.1,
          cloud_cover: 89,
          dew_point: 8.1,
          relative_humidity: null,
          visibility: 41100,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-05-27T19:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1019.6,
          sunshine: 13.0,
          temperature: 12.4,
          wind_direction: 276,
          wind_speed: 11.1,
          cloud_cover: 86,
          dew_point: 8.0,
          relative_humidity: null,
          visibility: 40000,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T20:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1020.0,
          sunshine: 12.0,
          temperature: 11.9,
          wind_direction: 267,
          wind_speed: 9.3,
          cloud_cover: 81,
          dew_point: 8.1,
          relative_humidity: null,
          visibility: 38300,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-05-27T21:00:00+02:00',
          source_id: 4089,
          precipitation: 0.8,
          pressure_msl: 1020.9,
          sunshine: 8.0,
          temperature: 11.2,
          wind_direction: 259,
          wind_speed: 7.4,
          cloud_cover: 75,
          dew_point: 8.1,
          relative_humidity: null,
          visibility: 38000,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-05-27T22:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1021.6,
          sunshine: 0.0,
          temperature: 10.4,
          wind_direction: 244,
          wind_speed: 7.4,
          cloud_cover: 71,
          dew_point: 8.0,
          relative_humidity: null,
          visibility: 37800,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-05-27T23:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1022.0,
          sunshine: 0.0,
          temperature: 9.6,
          wind_direction: 234,
          wind_speed: 7.4,
          cloud_cover: 67,
          dew_point: 8.0,
          relative_humidity: null,
          visibility: 38800,
          wind_gust_direction: null,
          wind_gust_speed: 13.0,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-05-28T00:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1022.5,
          sunshine: 0.0,
          temperature: 9.0,
          wind_direction: 227,
          wind_speed: 7.4,
          cloud_cover: 66,
          dew_point: 7.8,
          relative_humidity: null,
          visibility: 34100,
          wind_gust_direction: null,
          wind_gust_speed: 13.0,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-05-28T01:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1022.5,
          sunshine: 0.0,
          temperature: 8.7,
          wind_direction: 229,
          wind_speed: 7.4,
          cloud_cover: 61,
          dew_point: 7.5,
          relative_humidity: null,
          visibility: 33000,
          wind_gust_direction: null,
          wind_gust_speed: 11.1,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-05-28T02:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1022.4,
          sunshine: 0.0,
          temperature: 8.4,
          wind_direction: 229,
          wind_speed: 5.5,
          cloud_cover: 59,
          dew_point: 7.5,
          relative_humidity: null,
          visibility: 34500,
          wind_gust_direction: null,
          wind_gust_speed: 11.1,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-05-28T03:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1022.3,
          sunshine: 0.0,
          temperature: 7.9,
          wind_direction: 227,
          wind_speed: 5.5,
          cloud_cover: 57,
          dew_point: 7.3,
          relative_humidity: null,
          visibility: 33200,
          wind_gust_direction: null,
          wind_gust_speed: 11.1,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-05-28T04:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1022.3,
          sunshine: 0.0,
          temperature: 7.5,
          wind_direction: 224,
          wind_speed: 5.5,
          cloud_cover: 53,
          dew_point: 7.1,
          relative_humidity: null,
          visibility: 26800,
          wind_gust_direction: null,
          wind_gust_speed: 11.1,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-05-28T05:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1022.3,
          sunshine: 0.0,
          temperature: 7.5,
          wind_direction: 224,
          wind_speed: 5.5,
          cloud_cover: 51,
          dew_point: 6.9,
          relative_humidity: null,
          visibility: 23600,
          wind_gust_direction: null,
          wind_gust_speed: 11.1,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-05-28T06:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1022.3,
          sunshine: 11.0,
          temperature: 7.6,
          wind_direction: 215,
          wind_speed: 5.5,
          cloud_cover: 51,
          dew_point: 6.9,
          relative_humidity: null,
          visibility: 24300,
          wind_gust_direction: null,
          wind_gust_speed: 11.1,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-28T07:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1022.3,
          sunshine: 23.0,
          temperature: 8.7,
          wind_direction: 200,
          wind_speed: 5.5,
          cloud_cover: 51,
          dew_point: 7.0,
          relative_humidity: null,
          visibility: 23600,
          wind_gust_direction: null,
          wind_gust_speed: 11.1,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-28T08:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1021.9,
          sunshine: 35.0,
          temperature: 10.1,
          wind_direction: 180,
          wind_speed: 5.5,
          cloud_cover: 50,
          dew_point: 6.9,
          relative_humidity: null,
          visibility: 25200,
          wind_gust_direction: null,
          wind_gust_speed: 11.1,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-28T09:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1021.7,
          sunshine: 40.0,
          temperature: 11.5,
          wind_direction: 141,
          wind_speed: 7.4,
          cloud_cover: 50,
          dew_point: 6.9,
          relative_humidity: null,
          visibility: 26400,
          wind_gust_direction: null,
          wind_gust_speed: 13.0,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-28T10:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1021.3,
          sunshine: 42.0,
          temperature: 12.9,
          wind_direction: 112,
          wind_speed: 7.4,
          cloud_cover: 50,
          dew_point: 6.7,
          relative_humidity: null,
          visibility: 25700,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-28T11:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1020.7,
          sunshine: 42.0,
          temperature: 14.1,
          wind_direction: 80,
          wind_speed: 7.4,
          cloud_cover: 51,
          dew_point: 6.5,
          relative_humidity: null,
          visibility: 33500,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-28T12:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1020.2,
          sunshine: 38.0,
          temperature: 15.1,
          wind_direction: 58,
          wind_speed: 7.4,
          cloud_cover: 53,
          dew_point: 6.2,
          relative_humidity: null,
          visibility: 29800,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-28T13:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1019.6,
          sunshine: 37.0,
          temperature: 16.2,
          wind_direction: 35,
          wind_speed: 9.3,
          cloud_cover: 55,
          dew_point: 5.8,
          relative_humidity: null,
          visibility: 33700,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-28T14:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1019.0,
          sunshine: 38.0,
          temperature: 16.8,
          wind_direction: 46,
          wind_speed: 9.3,
          cloud_cover: 59,
          dew_point: 5.4,
          relative_humidity: null,
          visibility: 38000,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-28T15:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1018.3,
          sunshine: 39.0,
          temperature: 17.7,
          wind_direction: 40,
          wind_speed: 9.3,
          cloud_cover: 58,
          dew_point: 5.5,
          relative_humidity: null,
          visibility: 43900,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-28T16:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.7,
          sunshine: 40.0,
          temperature: 17.8,
          wind_direction: 33,
          wind_speed: 9.3,
          cloud_cover: 55,
          dew_point: 5.7,
          relative_humidity: null,
          visibility: 45300,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-28T17:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.4,
          sunshine: 39.0,
          temperature: 17.8,
          wind_direction: 36,
          wind_speed: 9.3,
          cloud_cover: 55,
          dew_point: 5.7,
          relative_humidity: null,
          visibility: 51700,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-28T18:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.4,
          sunshine: 38.0,
          temperature: 17.7,
          wind_direction: 42,
          wind_speed: 9.3,
          cloud_cover: 53,
          dew_point: 5.7,
          relative_humidity: null,
          visibility: 51300,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-28T19:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.8,
          sunshine: 37.0,
          temperature: 17.3,
          wind_direction: 46,
          wind_speed: 9.3,
          cloud_cover: 52,
          dew_point: 6.0,
          relative_humidity: null,
          visibility: 51900,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-28T20:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.7,
          sunshine: 31.0,
          temperature: 16.4,
          wind_direction: 50,
          wind_speed: 9.3,
          cloud_cover: 51,
          dew_point: 6.4,
          relative_humidity: null,
          visibility: 51000,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-28T21:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1018.3,
          sunshine: 20.0,
          temperature: 15.4,
          wind_direction: 57,
          wind_speed: 7.4,
          cloud_cover: 51,
          dew_point: 6.7,
          relative_humidity: null,
          visibility: 50800,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-05-28T22:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1019.0,
          sunshine: 0.0,
          temperature: 14.3,
          wind_direction: 69,
          wind_speed: 7.4,
          cloud_cover: 50,
          dew_point: 7.1,
          relative_humidity: null,
          visibility: 47000,
          wind_gust_direction: null,
          wind_gust_speed: 13.0,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-05-28T23:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1019.3,
          sunshine: 0.0,
          temperature: 13.1,
          wind_direction: 86,
          wind_speed: 7.4,
          cloud_cover: 50,
          dew_point: 7.3,
          relative_humidity: null,
          visibility: 44200,
          wind_gust_direction: null,
          wind_gust_speed: 11.1,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
      ],
      sources: [
        {
          id: 4089,
          dwd_station_id: '03379',
          observation_type: 'forecast',
          lat: 48.13,
          lon: 11.55,
          height: 520.0,
          station_name: 'MUENCHEN STADT',
          wmo_station_id: '10865',
          first_record: '2021-05-24T15:00:00+00:00',
          last_record: '2021-06-03T16:00:00+00:00',
          distance: 4330.0,
        },
      ],
    } as RawDayWeatherDataType
    return this.processWeatherData(tempWeatherData, 48.136, 11.577)
  }

  static processCurrentWeatherData(
    weatherData: RawCurrentWeatherDataType
  ): WeatherDataType {
    const weather = weatherData.weather
    return {
      timestamp: weather.timestamp,
      cloudCover: weather.cloud_cover,
      condition: weather.condition,
      dewPoint: weather.dew_point,
      precipitation: weather.precipitation_10,
      pressureMsl: weather.pressure_msl,
      relativeHumidity: weather.relative_humidity,
      visibility: weather.visibility,
      windDirection: weather.wind_direction_10,
      windSpeed: weather.wind_speed_10,
      windGustDirection: weather.wind_gust_direction_10,
      windGustSpeed: weather.wind_gust_speed_10,
      sunshine: weather.sunshine_30,
      temperature: Math.round(weather.temperature),
      icon: weather.icon,
    }
  }

  static processWeatherData(
    weatherData: RawDayWeatherDataType,
    lat,
    lon
  ): any[] {
    const mapped = weatherData.weather.map(weather => ({
      timestamp: weather.timestamp,
      cloudCover: weather.cloud_cover,
      condition: weather.condition,
      dewPoint: weather.dew_point,
      precipitation: weather.precipitation,
      pressureMsl: weather.pressure_msl,
      relativeHumidity: weather.relative_humidity,
      visibility: weather.visibility,
      windDirection: weather.wind_direction,
      windSpeed: weather.wind_speed,
      windGustDirection: weather.wind_gust_direction,
      windGustSpeed: weather.wind_gust_speed,
      sunshine: weather.sunshine,
      temperature: Math.round(weather.temperature),
      icon: weather.icon,
    }))

    const daysHash = {}
    mapped.forEach(element => {
      const day = element.timestamp.split('T')[0]
      if (!daysHash[day]) {
        daysHash[day] = []
      }
      daysHash[day].push(element)
    })

    let iconCount = {}
    const between = (val: number, left: number, right: number) =>
      val >= left && val <= right
    const getHours = (timestamp: string | number | Date) =>
      new Date(timestamp).getHours()
    const mostRelevantIcon = times => {
      iconCount = {}
      times.forEach(
        element =>
          (iconCount[element.icon] = iconCount[element.icon]
            ? iconCount[element.icon] + 1
            : 1)
      )
      return Object.entries(iconCount).reduce(
        (acc, [key, value]) => (value > acc[1] ? [key, value] : acc),
        ['clear-day', 0]
      )[0] as WeatherIconType
    }

    const dayGraphData = (times: WeatherDataType[]) => {
      let max = -Infinity,
        min = Infinity

      times.forEach(element => {
        if (element.temperature > max) max = element.temperature
        if (element.temperature < min) min = element.temperature
      })
      return {
        min: { temperature: min },
        max: { temperature: max },
        dayGraph: times.map(time => {
          return {
            timestamp: time.timestamp,
            temperature: Math.abs(
              (time.temperature - min) / (Math.abs(max) - Math.abs(min))
            ),
            precipitation: Math.min(Math.pow(time.precipitation, 1), 3)/3,
            sunniness: 1 - time.cloudCover / 100,
          }
        }),
      }
    }
    const result = Object.entries(daysHash).map(
      ([key, value]: [string, (WeatherDataType & { hours?: number })[]]) => {
        value = value.map(v => ({
          ...v,
          hours: getHours(v.timestamp),
        }))

        const day = new Date(key)
        const dayTimes = []
        const morningTimes = []
        const noonTimes = []
        const eveningTimes = []
        const dayLight = getSunriseSunset(day, lat, lon)

        value.forEach(v => {
          if (between(v.hours, 5, 22)) dayTimes.push(v)
          if (between(v.hours, 4, 9)) morningTimes.push(v)
          if (between(v.hours, 10, 17)) noonTimes.push(v)
          if (between(v.hours, 18, 22)) eveningTimes.push(v)
        })

        return {
          day,
          dayLight,
          morning: { icon: mostRelevantIcon(morningTimes) },
          noon: { icon: mostRelevantIcon(noonTimes) },
          evening: { icon: mostRelevantIcon(eveningTimes) },
          ...dayGraphData(dayTimes),
          data: value as WeatherDataType[],
        }
      }
    )

    return result
  }
}
