import type {
  WeatherDataType,
  RawCurrentWeatherDataType,
  RawDayWeatherDataType,
  DayWeatherDataType,
  WeatherIconType,
} from './weatherTypes'
import { currentWeatherData, weatherData } from '../stores/store'
import { getSunriseSunset } from './time'
const ENDPOINT = 'https://api.brightsky.dev/'
const MS_IN_HOUR = 1000 * 60 * 60
const DUMMY_DELAY = 500
let currentWeatherUrl = new URL(ENDPOINT + 'current_weather')
let weatherUrl = new URL(ENDPOINT + 'weather')

export default class Weather {
  static async getCurrentWeather(lat: number, lon: number) {
    currentWeatherUrl.search = new URLSearchParams({
      lat: lat.toString(),
      lon: lon.toString(),
      tz: 'Europe/Berlin',
    }).toString()
    const result = this.processCurrentWeatherData(
      await (await fetch(currentWeatherUrl.toString())).json()
    )

    currentWeatherData.set(result)
    return result
  }

  static formatTimeZoneOffset(date = new Date()) {
    let tzo = -date.getTimezoneOffset(),
      dif = tzo >= 0 ? '+' : '-'
    const pad = t => {
      const normalized = Math.floor(Math.abs(t))
      return (normalized < 10 ? '0' : '') + normalized
    }
    return dif + pad(tzo / 60) + ':' + pad(tzo % 60)
  }

  static addTimePortion(date = new Date(), beforeMidnight = false) {
    return (
      (beforeMidnight ? 'T23:59:00' : 'T00:00:00') +
      Weather.formatTimeZoneOffset(date)
    )
  }
  static dateToDateTime(date = new Date(), beforeMidnight = false) {
    return (
      new Intl.DateTimeFormat('eu').format(date).replace(/\//g, '-') +
      Weather.addTimePortion(date, beforeMidnight)
    )
  }
  static async getWeather(lat: number, lon: number, days = 3) {
    const now = new Date()
    const future = new Date(now.getTime() + MS_IN_HOUR * 24 * days - 10)

    weatherUrl.search = new URLSearchParams({
      lat: lat.toString(),
      lon: lon.toString(),
      days: days.toString(),
      date: Weather.dateToDateTime(now),
      last_date: Weather.dateToDateTime(future, true),
    }).toString()
    const result = this.processWeatherData(
      await (await fetch(weatherUrl.toString())).json(),
      lat,
      lon
    )
    weatherData.set(result)
    return result
  }

  static async getCurrentWeatherDummy(...arg) {
    const tempCurrentWeatherData = {
      weather: {
        source_id: 18377,
        timestamp: '2021-07-26T21:10:00+02:00',
        cloud_cover: 88,
        condition: 'rain',
        dew_point: 15.59,
        precipitation_10: 0.2,
        precipitation_30: 1.0,
        precipitation_60: 3.2,
        pressure_msl: 1014.9,
        relative_humidity: 93,
        visibility: 23823,
        wind_direction_10: 320,
        wind_direction_30: 317,
        wind_direction_60: 318,
        wind_speed_10: 6.8,
        wind_speed_30: 6.8,
        wind_speed_60: 10.4,
        wind_gust_direction_10: 330,
        wind_gust_direction_30: 330,
        wind_gust_direction_60: 290,
        wind_gust_speed_10: 11.5,
        wind_gust_speed_30: 12.2,
        wind_gust_speed_60: 27.7,
        sunshine_30: 0.0,
        sunshine_60: 0.0,
        temperature: 16.8,
        fallback_source_ids: {},
        icon: 'cloudy',
      },
      sources: [
        {
          id: 18377,
          dwd_station_id: '03379',
          observation_type: 'synop',
          lat: 48.1632,
          lon: 11.5429,
          height: 515.4,
          station_name: 'Muenchen-Stadt',
          wmo_station_id: '10865',
          first_record: '2021-07-25T13:30:00+00:00',
          last_record: '2021-07-26T19:10:00+00:00',
          distance: 3777.0,
        },
      ],
    } as RawCurrentWeatherDataType

    const processedWeatherData = this.processCurrentWeatherData(
      tempCurrentWeatherData
    )
    return new Promise<typeof processedWeatherData>(resolve =>
      setTimeout(() => {
        resolve(processedWeatherData)
      }, DUMMY_DELAY)
    )
  }

  static async getWeatherDummy(...arg) {
    const tempWeatherData = {
      weather: [
        {
          timestamp: '2021-07-26T00:00:00+02:00',
          source_id: 46586,
          precipitation: 0.0,
          pressure_msl: 1012.2,
          sunshine: 0.0,
          temperature: 18.4,
          wind_direction: 230,
          wind_speed: 6.5,
          cloud_cover: 62,
          dew_point: 16.0,
          relative_humidity: 86,
          visibility: 47910,
          wind_gust_direction: 220,
          wind_gust_speed: 13.7,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-26T01:00:00+02:00',
          source_id: 46586,
          precipitation: 0.0,
          pressure_msl: 1012.3,
          sunshine: 0.0,
          temperature: 17.3,
          wind_direction: 230,
          wind_speed: 4.0,
          cloud_cover: 87,
          dew_point: 15.7,
          relative_humidity: 90,
          visibility: 39390,
          wind_gust_direction: 210,
          wind_gust_speed: 8.6,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-26T02:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1012.3,
          sunshine: 0.0,
          temperature: 17.3,
          wind_direction: 210,
          wind_speed: 6.1,
          cloud_cover: 100,
          dew_point: 16.1,
          relative_humidity: 93,
          visibility: 30700,
          wind_gust_direction: null,
          wind_gust_speed: 9.0,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-26T03:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1012.2,
          sunshine: 0.0,
          temperature: 17.4,
          wind_direction: 180,
          wind_speed: 5.0,
          cloud_cover: 100,
          dew_point: 16.1,
          relative_humidity: 92,
          visibility: 31700,
          wind_gust_direction: null,
          wind_gust_speed: 11.2,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-26T04:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1012.1,
          sunshine: 0.0,
          temperature: 17.3,
          wind_direction: 240,
          wind_speed: 5.0,
          cloud_cover: 100,
          dew_point: 15.7,
          relative_humidity: 90,
          visibility: 33400,
          wind_gust_direction: null,
          wind_gust_speed: 11.9,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-26T05:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1012.1,
          sunshine: 0.0,
          temperature: 17.3,
          wind_direction: 170,
          wind_speed: 5.0,
          cloud_cover: 100,
          dew_point: 15.2,
          relative_humidity: 87,
          visibility: 39900,
          wind_gust_direction: null,
          wind_gust_speed: 11.2,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-26T06:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1012.7,
          sunshine: 0.0,
          temperature: 17.1,
          wind_direction: 260,
          wind_speed: 6.1,
          cloud_cover: 100,
          dew_point: 15.0,
          relative_humidity: 87,
          visibility: 44600,
          wind_gust_direction: null,
          wind_gust_speed: 11.9,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-26T07:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1012.6,
          sunshine: 0.0,
          temperature: 17.4,
          wind_direction: 190,
          wind_speed: 2.2,
          cloud_cover: 100,
          dew_point: 15.2,
          relative_humidity: 87,
          visibility: 37900,
          wind_gust_direction: null,
          wind_gust_speed: 9.0,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-26T08:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1012.7,
          sunshine: 0.0,
          temperature: 17.9,
          wind_direction: 240,
          wind_speed: 5.0,
          cloud_cover: 100,
          dew_point: 15.1,
          relative_humidity: 84,
          visibility: 45600,
          wind_gust_direction: null,
          wind_gust_speed: 10.1,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-26T09:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1012.6,
          sunshine: 4.0,
          temperature: 19.6,
          wind_direction: 130,
          wind_speed: 5.0,
          cloud_cover: 100,
          dew_point: 15.3,
          relative_humidity: 76,
          visibility: 47900,
          wind_gust_direction: null,
          wind_gust_speed: 10.1,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-26T10:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1012.6,
          sunshine: 13.0,
          temperature: 20.4,
          wind_direction: 300,
          wind_speed: 2.9,
          cloud_cover: 100,
          dew_point: 14.6,
          relative_humidity: 69,
          visibility: 61100,
          wind_gust_direction: null,
          wind_gust_speed: 11.2,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-26T11:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1012.1,
          sunshine: 19.0,
          temperature: 21.7,
          wind_direction: 340,
          wind_speed: 5.0,
          cloud_cover: 100,
          dew_point: 15.2,
          relative_humidity: 67,
          visibility: 33700,
          wind_gust_direction: null,
          wind_gust_speed: 10.1,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-26T12:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1011.9,
          sunshine: 60.0,
          temperature: 23.1,
          wind_direction: 200,
          wind_speed: 4.0,
          cloud_cover: 13,
          dew_point: 14.3,
          relative_humidity: 58,
          visibility: 51200,
          wind_gust_direction: null,
          wind_gust_speed: 13.0,
          condition: 'dry',
          icon: 'clear-day',
        },
        {
          timestamp: '2021-07-26T13:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1011.9,
          sunshine: 51.0,
          temperature: 23.3,
          wind_direction: 320,
          wind_speed: 7.9,
          cloud_cover: 0,
          dew_point: 14.2,
          relative_humidity: 57,
          visibility: 41500,
          wind_gust_direction: null,
          wind_gust_speed: 15.1,
          condition: 'dry',
          icon: 'clear-day',
        },
        {
          timestamp: '2021-07-26T14:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1011.3,
          sunshine: 40.0,
          temperature: 24.4,
          wind_direction: 70,
          wind_speed: 7.9,
          cloud_cover: 25,
          dew_point: 14.9,
          relative_humidity: 55,
          visibility: 45500,
          wind_gust_direction: null,
          wind_gust_speed: 14.0,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-26T15:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1010.4,
          sunshine: 57.0,
          temperature: 25.3,
          wind_direction: 110,
          wind_speed: 7.9,
          cloud_cover: 25,
          dew_point: 14.6,
          relative_humidity: 52,
          visibility: 55100,
          wind_gust_direction: null,
          wind_gust_speed: 16.9,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-26T16:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1009.7,
          sunshine: 57.0,
          temperature: 25.7,
          wind_direction: 60,
          wind_speed: 9.0,
          cloud_cover: 50,
          dew_point: 13.9,
          relative_humidity: 48,
          visibility: 54500,
          wind_gust_direction: null,
          wind_gust_speed: 20.9,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-26T17:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1009.7,
          sunshine: 10.0,
          temperature: 25.2,
          wind_direction: 30,
          wind_speed: 5.0,
          cloud_cover: 100,
          dew_point: 14.5,
          relative_humidity: 52,
          visibility: 56200,
          wind_gust_direction: null,
          wind_gust_speed: 16.9,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-26T18:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1009.8,
          sunshine: 0.0,
          temperature: 24.5,
          wind_direction: 360,
          wind_speed: 9.0,
          cloud_cover: 100,
          dew_point: 14.7,
          relative_humidity: 54,
          visibility: 56300,
          wind_gust_direction: null,
          wind_gust_speed: 18.0,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-26T19:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1010.7,
          sunshine: 0.0,
          temperature: 23.8,
          wind_direction: 350,
          wind_speed: 6.8,
          cloud_cover: 88,
          dew_point: 15.4,
          relative_humidity: 59,
          visibility: 48300,
          wind_gust_direction: null,
          wind_gust_speed: 18.0,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-26T20:00:00+02:00',
          source_id: 6269,
          precipitation: 4.2,
          pressure_msl: 1013.5,
          sunshine: 0.0,
          temperature: 19.2,
          wind_direction: 290,
          wind_speed: 19.1,
          cloud_cover: 88,
          dew_point: 17.6,
          relative_humidity: 90,
          visibility: 19300,
          wind_gust_direction: null,
          wind_gust_speed: 40.0,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-26T21:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1014.1,
          sunshine: 0.0,
          temperature: 18.6,
          wind_direction: 275,
          wind_speed: 11.1,
          cloud_cover: 92,
          dew_point: 16.7,
          relative_humidity: null,
          visibility: 31800,
          wind_gust_direction: null,
          wind_gust_speed: 29.6,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-26T22:00:00+02:00',
          source_id: 4089,
          precipitation: 2.6,
          pressure_msl: 1015.0,
          sunshine: 0.0,
          temperature: 17.7,
          wind_direction: 266,
          wind_speed: 7.4,
          cloud_cover: 92,
          dew_point: 15.7,
          relative_humidity: null,
          visibility: 25700,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-26T23:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1015.4,
          sunshine: 0.0,
          temperature: 17.3,
          wind_direction: 256,
          wind_speed: 7.4,
          cloud_cover: 98,
          dew_point: 15.7,
          relative_humidity: null,
          visibility: 32000,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'thunderstorm',
          icon: 'thunderstorm',
        },
        {
          timestamp: '2021-07-27T00:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.8,
          sunshine: 0.0,
          temperature: 17.0,
          wind_direction: 246,
          wind_speed: 7.4,
          cloud_cover: 95,
          dew_point: 15.6,
          relative_humidity: null,
          visibility: 30400,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'thunderstorm',
          icon: 'thunderstorm',
        },
        {
          timestamp: '2021-07-27T01:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.2,
          sunshine: 0.0,
          temperature: 16.6,
          wind_direction: 237,
          wind_speed: 7.4,
          cloud_cover: 93,
          dew_point: 15.3,
          relative_humidity: null,
          visibility: 32600,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-27T02:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.2,
          sunshine: 0.0,
          temperature: 16.4,
          wind_direction: 228,
          wind_speed: 7.4,
          cloud_cover: 91,
          dew_point: 15.1,
          relative_humidity: null,
          visibility: 33200,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-27T03:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.1,
          sunshine: 0.0,
          temperature: 16.3,
          wind_direction: 225,
          wind_speed: 7.4,
          cloud_cover: 92,
          dew_point: 15.0,
          relative_humidity: null,
          visibility: 30800,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-27T04:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.1,
          sunshine: 0.0,
          temperature: 16.2,
          wind_direction: 225,
          wind_speed: 7.4,
          cloud_cover: 90,
          dew_point: 14.9,
          relative_humidity: null,
          visibility: 28500,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-27T05:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.2,
          sunshine: 0.0,
          temperature: 16.4,
          wind_direction: 223,
          wind_speed: 7.4,
          cloud_cover: 86,
          dew_point: 14.7,
          relative_humidity: null,
          visibility: 28800,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-27T06:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.2,
          sunshine: 4.0,
          temperature: 16.5,
          wind_direction: 218,
          wind_speed: 7.4,
          cloud_cover: 78,
          dew_point: 14.7,
          relative_humidity: null,
          visibility: 29200,
          wind_gust_direction: null,
          wind_gust_speed: 13.0,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-27T07:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.1,
          sunshine: 12.0,
          temperature: 17.0,
          wind_direction: 216,
          wind_speed: 7.4,
          cloud_cover: 69,
          dew_point: 14.8,
          relative_humidity: null,
          visibility: 29200,
          wind_gust_direction: null,
          wind_gust_speed: 13.0,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-27T08:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.9,
          sunshine: 22.0,
          temperature: 18.0,
          wind_direction: 218,
          wind_speed: 5.5,
          cloud_cover: 64,
          dew_point: 14.7,
          relative_humidity: null,
          visibility: 30500,
          wind_gust_direction: null,
          wind_gust_speed: 13.0,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-27T09:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.8,
          sunshine: 27.0,
          temperature: 19.4,
          wind_direction: 226,
          wind_speed: 7.4,
          cloud_cover: 62,
          dew_point: 14.5,
          relative_humidity: null,
          visibility: 29800,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-27T10:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.6,
          sunshine: 32.0,
          temperature: 20.5,
          wind_direction: 243,
          wind_speed: 7.4,
          cloud_cover: 63,
          dew_point: 14.3,
          relative_humidity: null,
          visibility: 32300,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-27T11:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.2,
          sunshine: 36.0,
          temperature: 22.0,
          wind_direction: 289,
          wind_speed: 7.4,
          cloud_cover: 62,
          dew_point: 14.2,
          relative_humidity: null,
          visibility: 32300,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-27T12:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1014.8,
          sunshine: 37.0,
          temperature: 23.1,
          wind_direction: 21,
          wind_speed: 7.4,
          cloud_cover: 60,
          dew_point: 13.7,
          relative_humidity: null,
          visibility: 34400,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-27T13:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1014.1,
          sunshine: 39.0,
          temperature: 24.0,
          wind_direction: 42,
          wind_speed: 7.4,
          cloud_cover: 56,
          dew_point: 13.5,
          relative_humidity: null,
          visibility: 36600,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-27T14:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1013.6,
          sunshine: 42.0,
          temperature: 24.7,
          wind_direction: 32,
          wind_speed: 7.4,
          cloud_cover: 60,
          dew_point: 13.2,
          relative_humidity: null,
          visibility: 39700,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-27T15:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1013.0,
          sunshine: 39.0,
          temperature: 25.0,
          wind_direction: 35,
          wind_speed: 7.4,
          cloud_cover: 61,
          dew_point: 13.3,
          relative_humidity: null,
          visibility: 43500,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-27T16:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.6,
          sunshine: 37.0,
          temperature: 25.3,
          wind_direction: 34,
          wind_speed: 9.3,
          cloud_cover: 64,
          dew_point: 13.5,
          relative_humidity: null,
          visibility: 45800,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-27T17:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.3,
          sunshine: 30.0,
          temperature: 25.2,
          wind_direction: 45,
          wind_speed: 9.3,
          cloud_cover: 73,
          dew_point: 13.7,
          relative_humidity: null,
          visibility: 46000,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-27T18:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.2,
          sunshine: 25.0,
          temperature: 24.9,
          wind_direction: 51,
          wind_speed: 9.3,
          cloud_cover: 79,
          dew_point: 14.0,
          relative_humidity: null,
          visibility: 45500,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-27T19:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.2,
          sunshine: 19.0,
          temperature: 24.0,
          wind_direction: 69,
          wind_speed: 9.3,
          cloud_cover: 89,
          dew_point: 14.3,
          relative_humidity: null,
          visibility: 41100,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-27T20:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.4,
          sunshine: 12.0,
          temperature: 23.3,
          wind_direction: 112,
          wind_speed: 9.3,
          cloud_cover: 95,
          dew_point: 14.9,
          relative_humidity: null,
          visibility: 40900,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-27T21:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.7,
          sunshine: 7.0,
          temperature: 22.0,
          wind_direction: 135,
          wind_speed: 7.4,
          cloud_cover: 84,
          dew_point: 15.2,
          relative_humidity: null,
          visibility: 36000,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-27T22:00:00+02:00',
          source_id: 4089,
          precipitation: 0.7,
          pressure_msl: 1013.1,
          sunshine: 0.0,
          temperature: 21.0,
          wind_direction: 171,
          wind_speed: 7.4,
          cloud_cover: 88,
          dew_point: 15.3,
          relative_humidity: null,
          visibility: 39300,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-27T23:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1013.4,
          sunshine: 0.0,
          temperature: 20.2,
          wind_direction: 200,
          wind_speed: 7.4,
          cloud_cover: 84,
          dew_point: 15.6,
          relative_humidity: null,
          visibility: 35600,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-28T00:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1013.6,
          sunshine: 0.0,
          temperature: 19.6,
          wind_direction: 209,
          wind_speed: 7.4,
          cloud_cover: 88,
          dew_point: 15.6,
          relative_humidity: null,
          visibility: 35400,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-28T01:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1014.1,
          sunshine: 0.0,
          temperature: 19.0,
          wind_direction: 217,
          wind_speed: 7.4,
          cloud_cover: 95,
          dew_point: 15.6,
          relative_humidity: null,
          visibility: 34600,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-28T02:00:00+02:00',
          source_id: 4089,
          precipitation: 0.7,
          pressure_msl: 1014.2,
          sunshine: 0.0,
          temperature: 18.6,
          wind_direction: 214,
          wind_speed: 7.4,
          cloud_cover: 99,
          dew_point: 15.5,
          relative_humidity: null,
          visibility: 32900,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-28T03:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1014.2,
          sunshine: 0.0,
          temperature: 18.2,
          wind_direction: 213,
          wind_speed: 7.4,
          cloud_cover: 100,
          dew_point: 15.5,
          relative_humidity: null,
          visibility: 31100,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-28T04:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1014.3,
          sunshine: 0.0,
          temperature: 18.0,
          wind_direction: 215,
          wind_speed: 7.4,
          cloud_cover: 100,
          dew_point: 15.4,
          relative_humidity: null,
          visibility: 30200,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-28T05:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1014.3,
          sunshine: 0.0,
          temperature: 18.0,
          wind_direction: 210,
          wind_speed: 7.4,
          cloud_cover: 100,
          dew_point: 15.5,
          relative_humidity: null,
          visibility: 30400,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-28T06:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1014.4,
          sunshine: 0.0,
          temperature: 18.0,
          wind_direction: 213,
          wind_speed: 7.4,
          cloud_cover: 99,
          dew_point: 15.5,
          relative_humidity: null,
          visibility: 29400,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-28T07:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1014.5,
          sunshine: 4.0,
          temperature: 18.1,
          wind_direction: 214,
          wind_speed: 7.4,
          cloud_cover: 97,
          dew_point: 15.6,
          relative_humidity: null,
          visibility: 31200,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-28T08:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1014.5,
          sunshine: 4.0,
          temperature: 18.8,
          wind_direction: 218,
          wind_speed: 7.4,
          cloud_cover: 95,
          dew_point: 15.5,
          relative_humidity: null,
          visibility: 30400,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-28T09:00:00+02:00',
          source_id: 4089,
          precipitation: 0.2,
          pressure_msl: 1014.6,
          sunshine: 9.0,
          temperature: 19.5,
          wind_direction: 224,
          wind_speed: 9.3,
          cloud_cover: 95,
          dew_point: 15.5,
          relative_humidity: null,
          visibility: 31300,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-28T10:00:00+02:00',
          source_id: 4089,
          precipitation: 0.2,
          pressure_msl: 1014.6,
          sunshine: 12.0,
          temperature: 20.3,
          wind_direction: 227,
          wind_speed: 9.3,
          cloud_cover: 97,
          dew_point: 15.5,
          relative_humidity: null,
          visibility: 31200,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-28T11:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1014.5,
          sunshine: 16.0,
          temperature: 20.7,
          wind_direction: 231,
          wind_speed: 9.3,
          cloud_cover: 98,
          dew_point: 15.4,
          relative_humidity: null,
          visibility: 29900,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-28T12:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1014.6,
          sunshine: 17.0,
          temperature: 21.0,
          wind_direction: 236,
          wind_speed: 9.3,
          cloud_cover: 98,
          dew_point: 15.3,
          relative_humidity: null,
          visibility: 29100,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-28T13:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1014.6,
          sunshine: 19.0,
          temperature: 21.4,
          wind_direction: 247,
          wind_speed: 9.3,
          cloud_cover: 98,
          dew_point: 15.0,
          relative_humidity: null,
          visibility: 30500,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-28T14:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1014.2,
          sunshine: 17.0,
          temperature: 21.8,
          wind_direction: 243,
          wind_speed: 9.3,
          cloud_cover: 97,
          dew_point: 15.0,
          relative_humidity: null,
          visibility: 32700,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-28T15:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1013.8,
          sunshine: 17.0,
          temperature: 21.9,
          wind_direction: 238,
          wind_speed: 9.3,
          cloud_cover: 97,
          dew_point: 15.1,
          relative_humidity: null,
          visibility: 33900,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-28T16:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1013.8,
          sunshine: 18.0,
          temperature: 22.1,
          wind_direction: 235,
          wind_speed: 11.1,
          cloud_cover: 97,
          dew_point: 15.2,
          relative_humidity: null,
          visibility: 34400,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-28T17:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1013.6,
          sunshine: 16.0,
          temperature: 22.3,
          wind_direction: 235,
          wind_speed: 11.1,
          cloud_cover: 95,
          dew_point: 15.3,
          relative_humidity: null,
          visibility: 40000,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-28T18:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1013.4,
          sunshine: 18.0,
          temperature: 22.2,
          wind_direction: 222,
          wind_speed: 11.1,
          cloud_cover: 86,
          dew_point: 15.1,
          relative_humidity: null,
          visibility: 43600,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-28T19:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1013.4,
          sunshine: 20.0,
          temperature: 22.0,
          wind_direction: 209,
          wind_speed: 11.1,
          cloud_cover: 71,
          dew_point: 15.2,
          relative_humidity: null,
          visibility: 44100,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-28T20:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1013.7,
          sunshine: 19.0,
          temperature: 21.4,
          wind_direction: 199,
          wind_speed: 9.3,
          cloud_cover: 60,
          dew_point: 15.0,
          relative_humidity: null,
          visibility: 44300,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-28T21:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1014.0,
          sunshine: 14.0,
          temperature: 20.5,
          wind_direction: 189,
          wind_speed: 9.3,
          cloud_cover: 59,
          dew_point: 15.1,
          relative_humidity: null,
          visibility: 46300,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-28T22:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1014.5,
          sunshine: 0.0,
          temperature: 19.8,
          wind_direction: 188,
          wind_speed: 7.4,
          cloud_cover: 55,
          dew_point: 15.1,
          relative_humidity: null,
          visibility: 43500,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-28T23:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.0,
          sunshine: 0.0,
          temperature: 19.1,
          wind_direction: 194,
          wind_speed: 7.4,
          cloud_cover: 52,
          dew_point: 15.1,
          relative_humidity: null,
          visibility: 43600,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-29T00:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.4,
          sunshine: 0.0,
          temperature: 18.4,
          wind_direction: 199,
          wind_speed: 7.4,
          cloud_cover: 51,
          dew_point: 15.0,
          relative_humidity: null,
          visibility: 42700,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-29T01:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.6,
          sunshine: 0.0,
          temperature: 18.1,
          wind_direction: 202,
          wind_speed: 7.4,
          cloud_cover: 54,
          dew_point: 14.9,
          relative_humidity: null,
          visibility: 42000,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-29T02:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.8,
          sunshine: 0.0,
          temperature: 17.8,
          wind_direction: 206,
          wind_speed: 7.4,
          cloud_cover: 58,
          dew_point: 14.9,
          relative_humidity: null,
          visibility: 42300,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-29T03:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.8,
          sunshine: 0.0,
          temperature: 17.4,
          wind_direction: 208,
          wind_speed: 7.4,
          cloud_cover: 57,
          dew_point: 14.8,
          relative_humidity: null,
          visibility: 41200,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-29T04:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.8,
          sunshine: 0.0,
          temperature: 17.2,
          wind_direction: 208,
          wind_speed: 7.4,
          cloud_cover: 57,
          dew_point: 14.7,
          relative_humidity: null,
          visibility: 36100,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-29T05:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.7,
          sunshine: 0.0,
          temperature: 17.0,
          wind_direction: 205,
          wind_speed: 7.4,
          cloud_cover: 62,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 37800,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-29T06:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.8,
          sunshine: 5.0,
          temperature: 17.0,
          wind_direction: 204,
          wind_speed: 7.4,
          cloud_cover: 62,
          dew_point: 14.5,
          relative_humidity: null,
          visibility: 35300,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-29T07:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.9,
          sunshine: 13.0,
          temperature: 17.4,
          wind_direction: 207,
          wind_speed: 7.4,
          cloud_cover: 61,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 33800,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-29T08:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.6,
          sunshine: 20.0,
          temperature: 18.3,
          wind_direction: 208,
          wind_speed: 7.4,
          cloud_cover: 62,
          dew_point: 14.7,
          relative_humidity: null,
          visibility: 30200,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-29T09:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.3,
          sunshine: 26.0,
          temperature: 19.4,
          wind_direction: 214,
          wind_speed: 9.3,
          cloud_cover: 60,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 31400,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-29T10:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.2,
          sunshine: 30.0,
          temperature: 20.6,
          wind_direction: 220,
          wind_speed: 9.3,
          cloud_cover: 60,
          dew_point: 14.3,
          relative_humidity: null,
          visibility: 31900,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-29T11:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1014.9,
          sunshine: 34.0,
          temperature: 21.6,
          wind_direction: 230,
          wind_speed: 9.3,
          cloud_cover: 60,
          dew_point: 14.1,
          relative_humidity: null,
          visibility: 31300,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-29T12:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1014.5,
          sunshine: 36.0,
          temperature: 22.7,
          wind_direction: 241,
          wind_speed: 9.3,
          cloud_cover: 58,
          dew_point: 13.9,
          relative_humidity: null,
          visibility: 33800,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-29T13:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1013.9,
          sunshine: 35.0,
          temperature: 23.9,
          wind_direction: 257,
          wind_speed: 11.1,
          cloud_cover: 57,
          dew_point: 13.6,
          relative_humidity: null,
          visibility: 38500,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-29T14:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1013.3,
          sunshine: 35.0,
          temperature: 24.6,
          wind_direction: 248,
          wind_speed: 11.1,
          cloud_cover: 59,
          dew_point: 13.6,
          relative_humidity: null,
          visibility: 44000,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-29T15:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.9,
          sunshine: 36.0,
          temperature: 24.8,
          wind_direction: 250,
          wind_speed: 11.1,
          cloud_cover: 58,
          dew_point: 13.4,
          relative_humidity: null,
          visibility: 51000,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-29T16:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.4,
          sunshine: 35.0,
          temperature: 25.0,
          wind_direction: 254,
          wind_speed: 13.0,
          cloud_cover: 57,
          dew_point: 13.5,
          relative_humidity: null,
          visibility: 56400,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-29T17:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.2,
          sunshine: 35.0,
          temperature: 25.1,
          wind_direction: 255,
          wind_speed: 13.0,
          cloud_cover: 55,
          dew_point: 13.5,
          relative_humidity: null,
          visibility: 59300,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-29T18:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1011.9,
          sunshine: 35.0,
          temperature: 24.7,
          wind_direction: 243,
          wind_speed: 11.1,
          cloud_cover: 52,
          dew_point: 13.6,
          relative_humidity: null,
          visibility: 60800,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-29T19:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.0,
          sunshine: 34.0,
          temperature: 24.2,
          wind_direction: 236,
          wind_speed: 11.1,
          cloud_cover: 48,
          dew_point: 13.9,
          relative_humidity: null,
          visibility: 66100,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-29T20:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.1,
          sunshine: 28.0,
          temperature: 23.3,
          wind_direction: 212,
          wind_speed: 9.3,
          cloud_cover: 45,
          dew_point: 14.2,
          relative_humidity: null,
          visibility: 57900,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-29T21:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.6,
          sunshine: 17.0,
          temperature: 21.9,
          wind_direction: 196,
          wind_speed: 7.4,
          cloud_cover: 51,
          dew_point: 14.4,
          relative_humidity: null,
          visibility: 57900,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-29T22:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.8,
          sunshine: 0.0,
          temperature: 20.8,
          wind_direction: 189,
          wind_speed: 7.4,
          cloud_cover: 50,
          dew_point: 14.8,
          relative_humidity: null,
          visibility: 50300,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-29T23:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1013.3,
          sunshine: 0.0,
          temperature: 19.6,
          wind_direction: 191,
          wind_speed: 7.4,
          cloud_cover: 51,
          dew_point: 14.8,
          relative_humidity: null,
          visibility: 44900,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-30T00:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1013.9,
          sunshine: 0.0,
          temperature: 19.0,
          wind_direction: 199,
          wind_speed: 7.4,
          cloud_cover: 51,
          dew_point: 14.5,
          relative_humidity: null,
          visibility: 47700,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-30T01:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1013.7,
          sunshine: 0.0,
          temperature: 18.4,
          wind_direction: 209,
          wind_speed: 7.4,
          cloud_cover: 61,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 44100,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-30T02:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1013.6,
          sunshine: 0.0,
          temperature: 17.9,
          wind_direction: 204,
          wind_speed: 7.4,
          cloud_cover: 71,
          dew_point: 14.7,
          relative_humidity: null,
          visibility: 43600,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-30T03:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1013.3,
          sunshine: 0.0,
          temperature: 17.5,
          wind_direction: 206,
          wind_speed: 7.4,
          cloud_cover: 69,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 43000,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-30T04:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1013.4,
          sunshine: 0.0,
          temperature: 17.2,
          wind_direction: 202,
          wind_speed: 7.4,
          cloud_cover: 75,
          dew_point: 14.5,
          relative_humidity: null,
          visibility: 41900,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-30T05:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1013.1,
          sunshine: 0.0,
          temperature: 16.8,
          wind_direction: 194,
          wind_speed: 7.4,
          cloud_cover: 81,
          dew_point: 14.4,
          relative_humidity: null,
          visibility: 42800,
          wind_gust_direction: null,
          wind_gust_speed: 13.0,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-30T06:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1013.1,
          sunshine: 5.0,
          temperature: 16.9,
          wind_direction: 194,
          wind_speed: 5.5,
          cloud_cover: 81,
          dew_point: 14.4,
          relative_humidity: null,
          visibility: 39600,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-30T07:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.9,
          sunshine: 13.0,
          temperature: 17.2,
          wind_direction: 189,
          wind_speed: 7.4,
          cloud_cover: 81,
          dew_point: 14.5,
          relative_humidity: null,
          visibility: 39200,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-30T08:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.8,
          sunshine: 22.0,
          temperature: 18.4,
          wind_direction: 191,
          wind_speed: 7.4,
          cloud_cover: 80,
          dew_point: 14.3,
          relative_humidity: null,
          visibility: 36400,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-30T09:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.6,
          sunshine: 27.0,
          temperature: 20.0,
          wind_direction: 201,
          wind_speed: 7.4,
          cloud_cover: 74,
          dew_point: 14.1,
          relative_humidity: null,
          visibility: 37200,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-30T10:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.5,
          sunshine: 32.0,
          temperature: 21.4,
          wind_direction: 215,
          wind_speed: 9.3,
          cloud_cover: 63,
          dew_point: 14.0,
          relative_humidity: null,
          visibility: 35200,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-30T11:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.1,
          sunshine: 36.0,
          temperature: 22.4,
          wind_direction: 231,
          wind_speed: 9.3,
          cloud_cover: 60,
          dew_point: 14.1,
          relative_humidity: null,
          visibility: 34100,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-30T12:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1011.7,
          sunshine: 36.0,
          temperature: 23.5,
          wind_direction: 236,
          wind_speed: 11.1,
          cloud_cover: 60,
          dew_point: 14.0,
          relative_humidity: null,
          visibility: 35700,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-30T13:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1011.2,
          sunshine: 36.0,
          temperature: 24.2,
          wind_direction: 247,
          wind_speed: 11.1,
          cloud_cover: 60,
          dew_point: 13.6,
          relative_humidity: null,
          visibility: 35600,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-30T14:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1010.5,
          sunshine: 36.0,
          temperature: 24.5,
          wind_direction: 252,
          wind_speed: 13.0,
          cloud_cover: 64,
          dew_point: 13.6,
          relative_humidity: null,
          visibility: 42000,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-30T15:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1010.3,
          sunshine: 36.0,
          temperature: 25.1,
          wind_direction: 251,
          wind_speed: 13.0,
          cloud_cover: 67,
          dew_point: 13.6,
          relative_humidity: null,
          visibility: 50700,
          wind_gust_direction: null,
          wind_gust_speed: 29.6,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-30T16:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1010.0,
          sunshine: 33.0,
          temperature: 25.3,
          wind_direction: 248,
          wind_speed: 13.0,
          cloud_cover: 68,
          dew_point: 13.9,
          relative_humidity: null,
          visibility: 50800,
          wind_gust_direction: null,
          wind_gust_speed: 29.6,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-30T17:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1009.9,
          sunshine: 29.0,
          temperature: 25.1,
          wind_direction: 253,
          wind_speed: 13.0,
          cloud_cover: 71,
          dew_point: 14.0,
          relative_humidity: null,
          visibility: 58500,
          wind_gust_direction: null,
          wind_gust_speed: 29.6,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-30T18:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1010.0,
          sunshine: 27.0,
          temperature: 24.5,
          wind_direction: 247,
          wind_speed: 13.0,
          cloud_cover: 74,
          dew_point: 14.1,
          relative_humidity: null,
          visibility: 51200,
          wind_gust_direction: null,
          wind_gust_speed: 29.6,
          condition: 'rain',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-30T19:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1010.1,
          sunshine: 21.0,
          temperature: 23.5,
          wind_direction: 233,
          wind_speed: 11.1,
          cloud_cover: 74,
          dew_point: 14.2,
          relative_humidity: null,
          visibility: 49800,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-30T20:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1010.4,
          sunshine: 16.0,
          temperature: 22.3,
          wind_direction: 234,
          wind_speed: 11.1,
          cloud_cover: 79,
          dew_point: 14.3,
          relative_humidity: null,
          visibility: 46300,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'thunderstorm',
          icon: 'thunderstorm',
        },
        {
          timestamp: '2021-07-30T21:00:00+02:00',
          source_id: 4089,
          precipitation: 0.7,
          pressure_msl: 1011.2,
          sunshine: 10.0,
          temperature: 21.1,
          wind_direction: 228,
          wind_speed: 11.1,
          cloud_cover: 82,
          dew_point: 14.4,
          relative_humidity: null,
          visibility: 42300,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-30T22:00:00+02:00',
          source_id: 4089,
          precipitation: 0.8,
          pressure_msl: 1011.9,
          sunshine: 0.0,
          temperature: 20.0,
          wind_direction: 229,
          wind_speed: 11.1,
          cloud_cover: 83,
          dew_point: 14.5,
          relative_humidity: null,
          visibility: 40200,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-30T23:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1012.3,
          sunshine: 0.0,
          temperature: 19.0,
          wind_direction: 222,
          wind_speed: 11.1,
          cloud_cover: 78,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 43300,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-31T00:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1012.6,
          sunshine: 0.0,
          temperature: 18.3,
          wind_direction: 228,
          wind_speed: 9.3,
          cloud_cover: 83,
          dew_point: 14.4,
          relative_humidity: null,
          visibility: 47200,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T01:00:00+02:00',
          source_id: 4089,
          precipitation: 0.2,
          pressure_msl: 1012.9,
          sunshine: 0.0,
          temperature: 17.6,
          wind_direction: 225,
          wind_speed: 9.3,
          cloud_cover: 89,
          dew_point: 14.4,
          relative_humidity: null,
          visibility: 49700,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T02:00:00+02:00',
          source_id: 4089,
          precipitation: 0.2,
          pressure_msl: 1012.7,
          sunshine: 0.0,
          temperature: 17.3,
          wind_direction: 218,
          wind_speed: 9.3,
          cloud_cover: 85,
          dew_point: 14.0,
          relative_humidity: null,
          visibility: 50300,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T03:00:00+02:00',
          source_id: 4089,
          precipitation: 0.9,
          pressure_msl: 1012.6,
          sunshine: 0.0,
          temperature: 16.7,
          wind_direction: 223,
          wind_speed: 9.3,
          cloud_cover: 89,
          dew_point: 13.7,
          relative_humidity: null,
          visibility: 48300,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-31T04:00:00+02:00',
          source_id: 4089,
          precipitation: 0.7,
          pressure_msl: 1012.8,
          sunshine: 0.0,
          temperature: 16.1,
          wind_direction: 225,
          wind_speed: 9.3,
          cloud_cover: 87,
          dew_point: 13.5,
          relative_humidity: null,
          visibility: 49400,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-31T05:00:00+02:00',
          source_id: 4089,
          precipitation: 0.7,
          pressure_msl: 1012.8,
          sunshine: 0.0,
          temperature: 16.2,
          wind_direction: 229,
          wind_speed: 9.3,
          cloud_cover: 89,
          dew_point: 13.3,
          relative_humidity: null,
          visibility: 48800,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-31T06:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.8,
          sunshine: 2.0,
          temperature: 16.1,
          wind_direction: 224,
          wind_speed: 9.3,
          cloud_cover: 91,
          dew_point: 13.2,
          relative_humidity: null,
          visibility: 46500,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T07:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.8,
          sunshine: 7.0,
          temperature: 16.4,
          wind_direction: 234,
          wind_speed: 7.4,
          cloud_cover: 93,
          dew_point: 13.1,
          relative_humidity: null,
          visibility: 45500,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T08:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.4,
          sunshine: 14.0,
          temperature: 17.2,
          wind_direction: 234,
          wind_speed: 7.4,
          cloud_cover: 95,
          dew_point: 13.1,
          relative_humidity: null,
          visibility: 39000,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T09:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.3,
          sunshine: 16.0,
          temperature: 18.0,
          wind_direction: 249,
          wind_speed: 9.3,
          cloud_cover: 96,
          dew_point: 12.9,
          relative_humidity: null,
          visibility: 36600,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T10:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1012.1,
          sunshine: 19.0,
          temperature: 19.3,
          wind_direction: 261,
          wind_speed: 9.3,
          cloud_cover: 96,
          dew_point: 12.9,
          relative_humidity: null,
          visibility: 34400,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T11:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1011.8,
          sunshine: 21.0,
          temperature: 20.2,
          wind_direction: 266,
          wind_speed: 9.3,
          cloud_cover: 97,
          dew_point: 12.8,
          relative_humidity: null,
          visibility: 34700,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T12:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1011.9,
          sunshine: 23.0,
          temperature: 21.0,
          wind_direction: 260,
          wind_speed: 11.1,
          cloud_cover: 95,
          dew_point: 12.6,
          relative_humidity: null,
          visibility: 38200,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T13:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1011.1,
          sunshine: 24.0,
          temperature: 21.7,
          wind_direction: 265,
          wind_speed: 11.1,
          cloud_cover: 93,
          dew_point: 12.5,
          relative_humidity: null,
          visibility: 40300,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T14:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1010.5,
          sunshine: 25.0,
          temperature: 22.2,
          wind_direction: 266,
          wind_speed: 11.1,
          cloud_cover: 91,
          dew_point: 12.4,
          relative_humidity: null,
          visibility: 41900,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T15:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1010.2,
          sunshine: 24.0,
          temperature: 22.6,
          wind_direction: 270,
          wind_speed: 13.0,
          cloud_cover: 90,
          dew_point: 12.3,
          relative_humidity: null,
          visibility: 47800,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T16:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1009.9,
          sunshine: 23.0,
          temperature: 22.4,
          wind_direction: 279,
          wind_speed: 13.0,
          cloud_cover: 87,
          dew_point: 12.3,
          relative_humidity: null,
          visibility: 55300,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T17:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1009.7,
          sunshine: 22.0,
          temperature: 22.1,
          wind_direction: 278,
          wind_speed: 11.1,
          cloud_cover: 90,
          dew_point: 12.5,
          relative_humidity: null,
          visibility: 57000,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T18:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1009.5,
          sunshine: 18.0,
          temperature: 21.8,
          wind_direction: 271,
          wind_speed: 11.1,
          cloud_cover: 90,
          dew_point: 12.6,
          relative_humidity: null,
          visibility: 55600,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T19:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1010.1,
          sunshine: 19.0,
          temperature: 21.1,
          wind_direction: 269,
          wind_speed: 11.1,
          cloud_cover: 89,
          dew_point: 12.8,
          relative_humidity: null,
          visibility: 60400,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T20:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1010.7,
          sunshine: 13.0,
          temperature: 20.3,
          wind_direction: 254,
          wind_speed: 11.1,
          cloud_cover: 91,
          dew_point: 13.3,
          relative_humidity: null,
          visibility: 59200,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T21:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1010.8,
          sunshine: 9.0,
          temperature: 19.0,
          wind_direction: 250,
          wind_speed: 9.3,
          cloud_cover: 94,
          dew_point: 13.6,
          relative_humidity: null,
          visibility: 53700,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T22:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1011.5,
          sunshine: 0.0,
          temperature: 18.0,
          wind_direction: 243,
          wind_speed: 9.3,
          cloud_cover: 94,
          dew_point: 13.7,
          relative_humidity: null,
          visibility: 42200,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-31T23:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1012.5,
          sunshine: 0.0,
          temperature: 17.1,
          wind_direction: 240,
          wind_speed: 9.3,
          cloud_cover: 92,
          dew_point: 13.6,
          relative_humidity: null,
          visibility: 45800,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-08-01T00:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1012.6,
          sunshine: 0.0,
          temperature: 16.6,
          wind_direction: 238,
          wind_speed: 9.3,
          cloud_cover: 95,
          dew_point: 13.6,
          relative_humidity: null,
          visibility: 50300,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-08-01T01:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1012.4,
          sunshine: 0.0,
          temperature: 16.0,
          wind_direction: 234,
          wind_speed: 9.3,
          cloud_cover: 98,
          dew_point: 13.4,
          relative_humidity: null,
          visibility: 47500,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-08-01T02:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1012.2,
          sunshine: 0.0,
          temperature: 15.8,
          wind_direction: 239,
          wind_speed: 9.3,
          cloud_cover: 99,
          dew_point: 13.3,
          relative_humidity: null,
          visibility: 37600,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-08-01T03:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1012.4,
          sunshine: 0.0,
          temperature: 15.5,
          wind_direction: 234,
          wind_speed: 9.3,
          cloud_cover: 100,
          dew_point: 13.2,
          relative_humidity: null,
          visibility: 33800,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-08-01T04:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1012.5,
          sunshine: 0.0,
          temperature: 15.3,
          wind_direction: 230,
          wind_speed: 9.3,
          cloud_cover: 99,
          dew_point: 13.1,
          relative_humidity: null,
          visibility: 30100,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-08-01T05:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1012.3,
          sunshine: 0.0,
          temperature: 14.8,
          wind_direction: 229,
          wind_speed: 9.3,
          cloud_cover: 99,
          dew_point: 12.7,
          relative_humidity: null,
          visibility: 28400,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-08-01T06:00:00+02:00',
          source_id: 4089,
          precipitation: 0.8,
          pressure_msl: 1012.1,
          sunshine: 2.0,
          temperature: 14.7,
          wind_direction: 231,
          wind_speed: 9.3,
          cloud_cover: 99,
          dew_point: 12.6,
          relative_humidity: null,
          visibility: 31600,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-08-01T07:00:00+02:00',
          source_id: 4089,
          precipitation: 0.7,
          pressure_msl: 1012.1,
          sunshine: 4.0,
          temperature: 15.1,
          wind_direction: 224,
          wind_speed: 9.3,
          cloud_cover: 99,
          dew_point: 12.7,
          relative_humidity: null,
          visibility: 30700,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-08-01T08:00:00+02:00',
          source_id: 4089,
          precipitation: 0.7,
          pressure_msl: 1011.8,
          sunshine: 7.0,
          temperature: 15.3,
          wind_direction: 235,
          wind_speed: 9.3,
          cloud_cover: 99,
          dew_point: 12.8,
          relative_humidity: null,
          visibility: 24800,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-08-01T09:00:00+02:00',
          source_id: 4089,
          precipitation: 0.9,
          pressure_msl: 1011.6,
          sunshine: 11.0,
          temperature: 16.1,
          wind_direction: 247,
          wind_speed: 9.3,
          cloud_cover: 99,
          dew_point: 12.8,
          relative_humidity: null,
          visibility: 30100,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-08-01T10:00:00+02:00',
          source_id: 4089,
          precipitation: 1.1,
          pressure_msl: 1011.8,
          sunshine: 11.0,
          temperature: 16.7,
          wind_direction: 250,
          wind_speed: 11.1,
          cloud_cover: 99,
          dew_point: 12.8,
          relative_humidity: null,
          visibility: 30800,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-08-01T11:00:00+02:00',
          source_id: 4089,
          precipitation: 0.8,
          pressure_msl: 1011.8,
          sunshine: 11.0,
          temperature: 17.4,
          wind_direction: 256,
          wind_speed: 11.1,
          cloud_cover: 100,
          dew_point: 12.5,
          relative_humidity: null,
          visibility: 29400,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-08-01T12:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1011.2,
          sunshine: 13.0,
          temperature: 17.9,
          wind_direction: 257,
          wind_speed: 13.0,
          cloud_cover: 100,
          dew_point: 12.2,
          relative_humidity: null,
          visibility: 32900,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-08-01T13:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1011.4,
          sunshine: 14.0,
          temperature: 18.2,
          wind_direction: 261,
          wind_speed: 13.0,
          cloud_cover: 100,
          dew_point: 12.0,
          relative_humidity: null,
          visibility: 34800,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-08-01T14:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1010.8,
          sunshine: 13.0,
          temperature: 18.7,
          wind_direction: 260,
          wind_speed: 13.0,
          cloud_cover: 99,
          dew_point: 11.7,
          relative_humidity: null,
          visibility: 38000,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-08-01T15:00:00+02:00',
          source_id: 4089,
          precipitation: 0.7,
          pressure_msl: 1010.8,
          sunshine: 12.0,
          temperature: 18.8,
          wind_direction: 262,
          wind_speed: 13.0,
          cloud_cover: 97,
          dew_point: 11.9,
          relative_humidity: null,
          visibility: 38900,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-08-01T16:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1010.9,
          sunshine: 13.0,
          temperature: 18.8,
          wind_direction: 263,
          wind_speed: 13.0,
          cloud_cover: 94,
          dew_point: 11.1,
          relative_humidity: null,
          visibility: 44000,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-08-01T17:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1011.3,
          sunshine: 12.0,
          temperature: 18.5,
          wind_direction: 264,
          wind_speed: 13.0,
          cloud_cover: 90,
          dew_point: 11.2,
          relative_humidity: null,
          visibility: 43500,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-08-01T18:00:00+02:00',
          source_id: 4089,
          precipitation: 0.9,
          pressure_msl: 1011.4,
          sunshine: 11.0,
          temperature: 18.1,
          wind_direction: 257,
          wind_speed: 13.0,
          cloud_cover: 88,
          dew_point: 11.4,
          relative_humidity: null,
          visibility: 47000,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-08-01T19:00:00+02:00',
          source_id: 4089,
          precipitation: 0.7,
          pressure_msl: 1011.7,
          sunshine: 11.0,
          temperature: 18.2,
          wind_direction: 254,
          wind_speed: 11.1,
          cloud_cover: 84,
          dew_point: 11.0,
          relative_humidity: null,
          visibility: 48900,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-08-01T20:00:00+02:00',
          source_id: 4089,
          precipitation: 1.0,
          pressure_msl: 1012.0,
          sunshine: 11.0,
          temperature: 17.7,
          wind_direction: 246,
          wind_speed: 11.1,
          cloud_cover: 79,
          dew_point: 11.0,
          relative_humidity: null,
          visibility: 48500,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-08-01T21:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1012.5,
          sunshine: 7.0,
          temperature: 16.9,
          wind_direction: 231,
          wind_speed: 11.1,
          cloud_cover: 80,
          dew_point: 11.2,
          relative_humidity: null,
          visibility: 45100,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-08-01T22:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1013.0,
          sunshine: 0.0,
          temperature: 16.2,
          wind_direction: 224,
          wind_speed: 9.3,
          cloud_cover: 79,
          dew_point: 11.4,
          relative_humidity: null,
          visibility: 46400,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-08-01T23:00:00+02:00',
          source_id: 4089,
          precipitation: 0.7,
          pressure_msl: 1013.6,
          sunshine: 0.0,
          temperature: 15.7,
          wind_direction: 217,
          wind_speed: 9.3,
          cloud_cover: 79,
          dew_point: 11.8,
          relative_humidity: null,
          visibility: 48800,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'rain',
        },
      ],
      sources: [
        {
          id: 46586,
          dwd_station_id: '03379',
          observation_type: 'historical',
          lat: 48.1632,
          lon: 11.5429,
          height: 515.37,
          station_name: 'München-Stadt',
          wmo_station_id: '10865',
          first_record: '2010-01-01T00:00:00+00:00',
          last_record: '2021-07-25T23:00:00+00:00',
          distance: 3777.0,
        },
        {
          id: 6269,
          dwd_station_id: '03379',
          observation_type: 'current',
          lat: 48.13,
          lon: 11.55,
          height: 520.0,
          station_name: 'MUENCHEN STADT',
          wmo_station_id: '10865',
          first_record: '2021-07-24T20:00:00+00:00',
          last_record: '2021-07-26T18:00:00+00:00',
          distance: 2491.0,
        },
        {
          id: 4089,
          dwd_station_id: '03379',
          observation_type: 'forecast',
          lat: 48.13,
          lon: 11.55,
          height: 520.0,
          station_name: 'MUENCHEN STADT',
          wmo_station_id: '10865',
          first_record: '2021-07-26T17:00:00+00:00',
          last_record: '2021-08-05T18:00:00+00:00',
          distance: 2491.0,
        },
      ],
    } as RawDayWeatherDataType

    const processedWeatherData = this.processWeatherData(
      tempWeatherData,
      48.136,
      11.577
    )

    return new Promise<typeof processedWeatherData>(resolve =>
      setTimeout(() => {
        resolve(processedWeatherData)
      }, DUMMY_DELAY + 200)
    )
  }

  static processCurrentWeatherData(
    weatherData: RawCurrentWeatherDataType
  ): WeatherDataType {
    const weather = weatherData.weather
    return {
      timestamp: weather.timestamp,
      cloudCover: weather.cloud_cover,
      condition: weather.condition,
      dewPoint: weather.dew_point,
      precipitation: weather.precipitation_60,
      pressureMsl: weather.pressure_msl,
      relativeHumidity: weather.relative_humidity,
      visibility: weather.visibility,
      windDirection: weather.wind_direction_10,
      windSpeed: weather.wind_speed_10,
      windGustDirection: weather.wind_gust_direction_10,
      windGustSpeed: weather.wind_gust_speed_10,
      sunshine: weather.sunshine_30,
      temperature: Math.round(weather.temperature),
      icon: weather.icon,
    }
  }

  static processWeatherData(
    weatherData: RawDayWeatherDataType,
    lat,
    lon
  ): any[] {
    const mapped = weatherData.weather.map(weather => ({
      timestamp: weather.timestamp,
      cloudCover: weather.cloud_cover,
      condition: weather.condition,
      dewPoint: weather.dew_point,
      precipitation: weather.precipitation,
      pressureMsl: weather.pressure_msl,
      relativeHumidity: weather.relative_humidity,
      visibility: weather.visibility,
      windDirection: weather.wind_direction,
      windSpeed: weather.wind_speed,
      windGustDirection: weather.wind_gust_direction,
      windGustSpeed: weather.wind_gust_speed,
      sunshine: weather.sunshine,
      temperature: Math.round(weather.temperature),
      icon: weather.icon,
    }))

    const daysHash = {}
    mapped.forEach(element => {
      const day = element.timestamp.split('T')[0]
      if (!daysHash[day]) {
        daysHash[day] = []
      }
      daysHash[day].push(element)
    })

    let iconCount = {}
    const between = (val: number, left: number, right: number) =>
      val >= left && val <= right
    const getHours = (timestamp: string | number | Date) =>
      new Date(timestamp).getHours()
    const mostRelevantIcon = times => {
      const iconValue = (icon: WeatherIconType) => {
        switch (icon) {
          case 'thunderstorm':
          case 'hail':
            return 12
          default:
            return 1
        }
      }
      iconCount = {}
      times.forEach(
        element =>
          (iconCount[element.icon] =
            iconValue(element.icon) + (iconCount[element.icon] ?? 0))
      )
      return Object.entries(iconCount).reduce(
        (acc, [key, value]) => (value > acc[1] ? [key, value] : acc),
        ['clear-day', 0]
      )[0] as WeatherIconType
    }

    const getIconColor = (icon: WeatherIconType) => {
      switch (icon) {
        case 'rain':
        case 'sleet':
        case 'hail':
        case 'snow':
        case 'thunderstorm':
          return '#0066ED'
        case 'clear-day':
        case 'clear-night':
        case 'partly-cloudy-day':
        case 'partly-cloudy-night':
          return '#FFB901'
        default:
          return '#444444'
      }
    }

    const dayGraphData = (times: WeatherDataType[]) => {
      let max = -Infinity,
        min = Infinity

      times.forEach(element => {
        if (element.temperature > max) max = element.temperature
        if (element.temperature < min) min = element.temperature
      })
      return {
        min: { temperature: min },
        max: { temperature: max },
        dayGraph: times.map(time => {
          return {
            timestamp: time.timestamp,
            temperature: Math.abs(
              (time.temperature - min) / (Math.abs(max) - Math.abs(min))
            ),
            precipitation:
              Math.min(Math.pow(Math.sqrt(time.precipitation) * 1.7, 2), 6) / 6,
            sunniness: 1 - time.cloudCover / 100,
          }
        }),
      }
    }
    const result = Object.entries(daysHash).map(
      ([key, value]: [string, (WeatherDataType & { hours?: number })[]]) => {
        value = value.map(v => ({
          ...v,
          hours: getHours(v.timestamp),
        }))

        const day = new Date(key)
        const dayTimes = []
        const morningTimes = []
        const noonTimes = []
        const eveningTimes = []
        const dayLight = getSunriseSunset(day, lat, lon)

        value.forEach(v => {
          if (between(v.hours, 4, 22)) dayTimes.push(v)
          if (between(v.hours, 4, 9)) morningTimes.push(v)
          if (between(v.hours, 10, 17)) noonTimes.push(v)
          if (between(v.hours, 18, 22)) eveningTimes.push(v)
        })

        return {
          day,
          dayLight,
          dayParts: [morningTimes, noonTimes, eveningTimes].map(t => {
            const icon = mostRelevantIcon(t)
            return { icon, color: getIconColor(icon) }
          }),
          ...dayGraphData(dayTimes),
          data: value as WeatherDataType[],
        }
      }
    )

    return result
  }
}
