import type {
  WeatherDataType,
  RawCurrentWeatherDataType,
  RawDayWeatherDataType,
  DayWeatherDataType,
  WeatherIconType,
} from './weatherTypes'
import { currentWeatherData, weatherData } from '../stores/store'
import { getSunriseSunset } from './time'
const ENDPOINT = 'https://api.brightsky.dev/'
const MS_IN_HOUR = 1000 * 60 * 60
const DUMMY_DELAY = 500
let currentWeatherUrl = new URL(ENDPOINT + 'current_weather')
let weatherUrl = new URL(ENDPOINT + 'weather')

export default class Weather {
  static async getCurrentWeather(lat: number, lon: number) {
    currentWeatherUrl.search = new URLSearchParams({
      lat: lat.toString(),
      lon: lon.toString(),
      tz: 'Europe/Berlin',
    }).toString()
    const result = this.processCurrentWeatherData(
      await (await fetch(currentWeatherUrl.toString())).json()
    )

    currentWeatherData.set(result)
    return result
  }

  static formatTimeZoneOffset(date = new Date()) {
    let tzo = -date.getTimezoneOffset(),
      dif = tzo >= 0 ? '+' : '-'
    const pad = t => {
      const normalized = Math.floor(Math.abs(t))
      return (normalized < 10 ? '0' : '') + normalized
    }
    return dif + pad(tzo / 60) + ':' + pad(tzo % 60)
  }

  static addTimePortion(date = new Date(), beforeMidnight = false) {
    return (
      (beforeMidnight ? 'T23:59:00' : 'T00:00:00') +
      Weather.formatTimeZoneOffset(date)
    )
  }
  static dateToDateTime(date = new Date(), beforeMidnight = false) {
    return (
      new Intl.DateTimeFormat('eu').format(date).replace(/\//g, '-') +
      Weather.addTimePortion(date, beforeMidnight)
    )
  }
  static async getWeather(lat: number, lon: number, days = 3) {
    const now = new Date()
    const future = new Date(now.getTime() + MS_IN_HOUR * 24 * days - 10)

    weatherUrl.search = new URLSearchParams({
      lat: lat.toString(),
      lon: lon.toString(),
      days: days.toString(),
      date: Weather.dateToDateTime(now),
      last_date: Weather.dateToDateTime(future, true),
    }).toString()
    const result = this.processWeatherData(
      await (await fetch(weatherUrl.toString())).json(),
      lat,
      lon
    )
    weatherData.set(result)
    return result
  }

  static async getCurrentWeatherDummy(...arg) {
    const tempCurrentWeatherData = {
      weather: {
        source_id: 18377,
        timestamp: '2021-07-12T17:30:00+02:00',
        cloud_cover: 0,
        condition: 'dry',
        dew_point: 13.35,
        precipitation_10: 0.0,
        precipitation_30: 0.0,
        precipitation_60: 0.0,
        pressure_msl: 1007.4,
        relative_humidity: 47,
        visibility: 75000,
        wind_direction_10: 50,
        wind_direction_30: 53,
        wind_direction_60: 53,
        wind_speed_10: 15.5,
        wind_speed_30: 14.8,
        wind_speed_60: 14.8,
        wind_gust_direction_10: 40,
        wind_gust_direction_30: 40,
        wind_gust_direction_60: 40,
        wind_gust_speed_10: 24.8,
        wind_gust_speed_30: 24.8,
        wind_gust_speed_60: 24.8,
        sunshine_30: 30.0,
        sunshine_60: 59.0,
        temperature: 25.6,
        fallback_source_ids: {},
        icon: 'clear-day',
      },
      sources: [
        {
          id: 18377,
          dwd_station_id: '03379',
          observation_type: 'synop',
          lat: 48.1632,
          lon: 11.5429,
          height: 515.4,
          station_name: 'Muenchen-Stadt',
          wmo_station_id: '10865',
          first_record: '2021-07-11T09:30:00+00:00',
          last_record: '2021-07-12T15:30:00+00:00',
          distance: 3777.0,
        },
      ],
    } as RawCurrentWeatherDataType

    const processedWeatherData = this.processCurrentWeatherData(
      tempCurrentWeatherData
    )
    return new Promise<typeof processedWeatherData>(resolve =>
      setTimeout(() => {
        resolve(processedWeatherData)
      }, DUMMY_DELAY)
    )
  }

  static async getWeatherDummy(...arg) {
    const tempWeatherData = {
      weather: [
        {
          timestamp: '2021-07-12T00:00:00+02:00',
          source_id: 46586,
          precipitation: 0.0,
          pressure_msl: 1016.4,
          sunshine: 0.0,
          temperature: 14.3,
          wind_direction: 90,
          wind_speed: 5.8,
          cloud_cover: 0,
          dew_point: 12.8,
          relative_humidity: 91,
          visibility: 59520,
          wind_gust_direction: 100,
          wind_gust_speed: 9.7,
          condition: 'dry',
          icon: 'clear-night',
        },
        {
          timestamp: '2021-07-12T01:00:00+02:00',
          source_id: 46586,
          precipitation: 0.0,
          pressure_msl: 1016.2,
          sunshine: 0.0,
          temperature: 13.6,
          wind_direction: 110,
          wind_speed: 5.0,
          cloud_cover: 0,
          dew_point: 12.2,
          relative_humidity: 91,
          visibility: 60420,
          wind_gust_direction: 130,
          wind_gust_speed: 8.6,
          condition: 'dry',
          icon: 'clear-night',
        },
        {
          timestamp: '2021-07-12T02:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1016.2,
          sunshine: 0.0,
          temperature: 13.1,
          wind_direction: 70,
          wind_speed: 5.0,
          cloud_cover: 0,
          dew_point: 12.0,
          relative_humidity: 93,
          visibility: 43300,
          wind_gust_direction: null,
          wind_gust_speed: 9.0,
          condition: 'dry',
          icon: 'clear-night',
        },
        {
          timestamp: '2021-07-12T03:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1015.9,
          sunshine: 0.0,
          temperature: 12.6,
          wind_direction: 60,
          wind_speed: 2.9,
          cloud_cover: 0,
          dew_point: 11.6,
          relative_humidity: 94,
          visibility: 39200,
          wind_gust_direction: null,
          wind_gust_speed: 6.1,
          condition: 'dry',
          icon: 'clear-night',
        },
        {
          timestamp: '2021-07-12T04:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1015.3,
          sunshine: 0.0,
          temperature: 12.8,
          wind_direction: 100,
          wind_speed: 6.1,
          cloud_cover: 0,
          dew_point: 11.9,
          relative_humidity: 94,
          visibility: 41600,
          wind_gust_direction: null,
          wind_gust_speed: 7.9,
          condition: 'dry',
          icon: 'clear-night',
        },
        {
          timestamp: '2021-07-12T05:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1014.9,
          sunshine: 0.0,
          temperature: 12.2,
          wind_direction: 60,
          wind_speed: 4.0,
          cloud_cover: 0,
          dew_point: 11.4,
          relative_humidity: 95,
          visibility: 36000,
          wind_gust_direction: null,
          wind_gust_speed: 7.9,
          condition: 'dry',
          icon: 'clear-night',
        },
        {
          timestamp: '2021-07-12T06:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1015.1,
          sunshine: 10.0,
          temperature: 11.9,
          wind_direction: 70,
          wind_speed: 4.0,
          cloud_cover: 0,
          dew_point: 11.2,
          relative_humidity: 95,
          visibility: 31800,
          wind_gust_direction: null,
          wind_gust_speed: 6.8,
          condition: 'dry',
          icon: 'clear-day',
        },
        {
          timestamp: '2021-07-12T07:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1014.4,
          sunshine: 60.0,
          temperature: 13.4,
          wind_direction: 80,
          wind_speed: 5.0,
          cloud_cover: 0,
          dew_point: 12.5,
          relative_humidity: 94,
          visibility: 43200,
          wind_gust_direction: null,
          wind_gust_speed: 7.9,
          condition: 'dry',
          icon: 'clear-day',
        },
        {
          timestamp: '2021-07-12T08:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1014.0,
          sunshine: 60.0,
          temperature: 14.7,
          wind_direction: 80,
          wind_speed: 5.0,
          cloud_cover: 0,
          dew_point: 12.6,
          relative_humidity: 87,
          visibility: 34400,
          wind_gust_direction: null,
          wind_gust_speed: 11.9,
          condition: 'dry',
          icon: 'clear-day',
        },
        {
          timestamp: '2021-07-12T09:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1013.1,
          sunshine: 60.0,
          temperature: 17.7,
          wind_direction: 100,
          wind_speed: 11.2,
          cloud_cover: 0,
          dew_point: 12.6,
          relative_humidity: 72,
          visibility: 68000,
          wind_gust_direction: null,
          wind_gust_speed: 18.0,
          condition: 'dry',
          icon: 'clear-day',
        },
        {
          timestamp: '2021-07-12T10:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1012.4,
          sunshine: 60.0,
          temperature: 19.4,
          wind_direction: 90,
          wind_speed: 10.1,
          cloud_cover: 0,
          dew_point: 12.0,
          relative_humidity: 62,
          visibility: 65700,
          wind_gust_direction: null,
          wind_gust_speed: 20.2,
          condition: 'dry',
          icon: 'clear-day',
        },
        {
          timestamp: '2021-07-12T11:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1011.2,
          sunshine: 60.0,
          temperature: 21.8,
          wind_direction: 70,
          wind_speed: 6.8,
          cloud_cover: 0,
          dew_point: 14.1,
          relative_humidity: 62,
          visibility: 75000,
          wind_gust_direction: null,
          wind_gust_speed: 24.8,
          condition: 'dry',
          icon: 'clear-day',
        },
        {
          timestamp: '2021-07-12T12:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1010.7,
          sunshine: 60.0,
          temperature: 22.4,
          wind_direction: 90,
          wind_speed: 15.1,
          cloud_cover: 0,
          dew_point: 12.0,
          relative_humidity: 52,
          visibility: 71500,
          wind_gust_direction: null,
          wind_gust_speed: 28.1,
          condition: 'dry',
          icon: 'clear-day',
        },
        {
          timestamp: '2021-07-12T13:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1009.8,
          sunshine: 60.0,
          temperature: 24.2,
          wind_direction: 90,
          wind_speed: 10.1,
          cloud_cover: 0,
          dew_point: 13.2,
          relative_humidity: 50,
          visibility: 75000,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'dry',
          icon: 'clear-day',
        },
        {
          timestamp: '2021-07-12T14:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1009.2,
          sunshine: 60.0,
          temperature: 25.1,
          wind_direction: 70,
          wind_speed: 11.2,
          cloud_cover: 38,
          dew_point: 14.0,
          relative_humidity: 50,
          visibility: 52700,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-12T15:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1008.4,
          sunshine: 60.0,
          temperature: 25.1,
          wind_direction: 60,
          wind_speed: 15.1,
          cloud_cover: 0,
          dew_point: 13.8,
          relative_humidity: 50,
          visibility: 58000,
          wind_gust_direction: null,
          wind_gust_speed: 29.9,
          condition: 'dry',
          icon: 'clear-day',
        },
        {
          timestamp: '2021-07-12T16:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1008.2,
          sunshine: 60.0,
          temperature: 25.3,
          wind_direction: 50,
          wind_speed: 15.1,
          cloud_cover: 0,
          dew_point: 14.6,
          relative_humidity: 52,
          visibility: 54900,
          wind_gust_direction: null,
          wind_gust_speed: 33.1,
          condition: 'dry',
          icon: 'clear-day',
        },
        {
          timestamp: '2021-07-12T17:00:00+02:00',
          source_id: 6269,
          precipitation: 0.0,
          pressure_msl: 1007.5,
          sunshine: 59.0,
          temperature: 26.1,
          wind_direction: 50,
          wind_speed: 15.1,
          cloud_cover: 38,
          dew_point: 14.8,
          relative_humidity: 50,
          visibility: 55400,
          wind_gust_direction: null,
          wind_gust_speed: 29.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-12T18:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1007.2,
          sunshine: 46.0,
          temperature: 25.7,
          wind_direction: 57,
          wind_speed: 14.8,
          cloud_cover: 43,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 52500,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-12T19:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1007.5,
          sunshine: 40.0,
          temperature: 24.7,
          wind_direction: 54,
          wind_speed: 13.0,
          cloud_cover: 52,
          dew_point: 14.3,
          relative_humidity: null,
          visibility: 48600,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-12T20:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1007.9,
          sunshine: 29.0,
          temperature: 23.6,
          wind_direction: 56,
          wind_speed: 11.1,
          cloud_cover: 61,
          dew_point: 14.0,
          relative_humidity: null,
          visibility: 50900,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-12T21:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1008.5,
          sunshine: 17.0,
          temperature: 22.6,
          wind_direction: 57,
          wind_speed: 9.3,
          cloud_cover: 65,
          dew_point: 13.8,
          relative_humidity: null,
          visibility: 50400,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-12T22:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1008.8,
          sunshine: 6.0,
          temperature: 21.5,
          wind_direction: 57,
          wind_speed: 7.4,
          cloud_cover: 74,
          dew_point: 14.0,
          relative_humidity: null,
          visibility: 45800,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-12T23:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1009.0,
          sunshine: 0.0,
          temperature: 20.3,
          wind_direction: 68,
          wind_speed: 9.3,
          cloud_cover: 67,
          dew_point: 14.0,
          relative_humidity: null,
          visibility: 42900,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-13T00:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1008.6,
          sunshine: 0.0,
          temperature: 19.6,
          wind_direction: 65,
          wind_speed: 7.4,
          cloud_cover: 70,
          dew_point: 13.8,
          relative_humidity: null,
          visibility: 40900,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-13T01:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1008.4,
          sunshine: 0.0,
          temperature: 18.9,
          wind_direction: 62,
          wind_speed: 7.4,
          cloud_cover: 68,
          dew_point: 13.7,
          relative_humidity: null,
          visibility: 39400,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-13T02:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1008.0,
          sunshine: 0.0,
          temperature: 18.2,
          wind_direction: 67,
          wind_speed: 7.4,
          cloud_cover: 64,
          dew_point: 13.6,
          relative_humidity: null,
          visibility: 38500,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-13T03:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1007.6,
          sunshine: 0.0,
          temperature: 17.8,
          wind_direction: 71,
          wind_speed: 7.4,
          cloud_cover: 62,
          dew_point: 13.7,
          relative_humidity: null,
          visibility: 32400,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-13T04:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1007.1,
          sunshine: 0.0,
          temperature: 17.5,
          wind_direction: 51,
          wind_speed: 7.4,
          cloud_cover: 67,
          dew_point: 13.7,
          relative_humidity: null,
          visibility: 29000,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-13T05:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1007.0,
          sunshine: 0.0,
          temperature: 17.2,
          wind_direction: 34,
          wind_speed: 5.5,
          cloud_cover: 67,
          dew_point: 13.7,
          relative_humidity: null,
          visibility: 28400,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-13T06:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1006.9,
          sunshine: 6.0,
          temperature: 17.2,
          wind_direction: 38,
          wind_speed: 5.5,
          cloud_cover: 66,
          dew_point: 13.6,
          relative_humidity: null,
          visibility: 26600,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-13T07:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1006.7,
          sunshine: 12.0,
          temperature: 17.4,
          wind_direction: 8,
          wind_speed: 7.4,
          cloud_cover: 72,
          dew_point: 13.7,
          relative_humidity: null,
          visibility: 24400,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-13T08:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1006.4,
          sunshine: 20.0,
          temperature: 18.4,
          wind_direction: 292,
          wind_speed: 9.3,
          cloud_cover: 76,
          dew_point: 13.8,
          relative_humidity: null,
          visibility: 24300,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-13T09:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1006.3,
          sunshine: 24.0,
          temperature: 19.4,
          wind_direction: 266,
          wind_speed: 9.3,
          cloud_cover: 76,
          dew_point: 14.1,
          relative_humidity: null,
          visibility: 24200,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-13T10:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1006.2,
          sunshine: 26.0,
          temperature: 20.2,
          wind_direction: 264,
          wind_speed: 11.1,
          cloud_cover: 80,
          dew_point: 14.2,
          relative_humidity: null,
          visibility: 30200,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-13T11:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1006.2,
          sunshine: 28.0,
          temperature: 21.1,
          wind_direction: 265,
          wind_speed: 13.0,
          cloud_cover: 89,
          dew_point: 14.4,
          relative_humidity: null,
          visibility: 31100,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-13T12:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1006.6,
          sunshine: 29.0,
          temperature: 21.6,
          wind_direction: 272,
          wind_speed: 14.8,
          cloud_cover: 88,
          dew_point: 14.3,
          relative_humidity: null,
          visibility: 33300,
          wind_gust_direction: null,
          wind_gust_speed: 29.6,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-13T13:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1006.8,
          sunshine: 26.0,
          temperature: 22.0,
          wind_direction: 274,
          wind_speed: 14.8,
          cloud_cover: 87,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 29800,
          wind_gust_direction: null,
          wind_gust_speed: 31.5,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-13T14:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1006.8,
          sunshine: 24.0,
          temperature: 21.3,
          wind_direction: 277,
          wind_speed: 16.7,
          cloud_cover: 92,
          dew_point: 14.4,
          relative_humidity: null,
          visibility: 30200,
          wind_gust_direction: null,
          wind_gust_speed: 33.3,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-13T15:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1007.0,
          sunshine: 22.0,
          temperature: 20.8,
          wind_direction: 279,
          wind_speed: 16.7,
          cloud_cover: 93,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 30300,
          wind_gust_direction: null,
          wind_gust_speed: 33.3,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-13T16:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1007.6,
          sunshine: 14.0,
          temperature: 20.1,
          wind_direction: 273,
          wind_speed: 16.7,
          cloud_cover: 97,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 28000,
          wind_gust_direction: null,
          wind_gust_speed: 35.2,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-13T17:00:00+02:00',
          source_id: 4089,
          precipitation: 1.1,
          pressure_msl: 1008.1,
          sunshine: 10.0,
          temperature: 19.5,
          wind_direction: 268,
          wind_speed: 16.7,
          cloud_cover: 98,
          dew_point: 14.5,
          relative_humidity: null,
          visibility: 25400,
          wind_gust_direction: null,
          wind_gust_speed: 35.2,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-13T18:00:00+02:00',
          source_id: 4089,
          precipitation: 1.2,
          pressure_msl: 1009.4,
          sunshine: 2.0,
          temperature: 18.5,
          wind_direction: 270,
          wind_speed: 14.8,
          cloud_cover: 100,
          dew_point: 14.8,
          relative_humidity: null,
          visibility: 21700,
          wind_gust_direction: null,
          wind_gust_speed: 33.3,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-13T19:00:00+02:00',
          source_id: 4089,
          precipitation: 1.0,
          pressure_msl: 1009.8,
          sunshine: 0.0,
          temperature: 17.8,
          wind_direction: 258,
          wind_speed: 13.0,
          cloud_cover: 100,
          dew_point: 14.9,
          relative_humidity: null,
          visibility: 21500,
          wind_gust_direction: null,
          wind_gust_speed: 31.5,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-13T20:00:00+02:00',
          source_id: 4089,
          precipitation: 1.1,
          pressure_msl: 1010.0,
          sunshine: 0.0,
          temperature: 17.3,
          wind_direction: 258,
          wind_speed: 13.0,
          cloud_cover: 100,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 19400,
          wind_gust_direction: null,
          wind_gust_speed: 29.6,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-13T21:00:00+02:00',
          source_id: 4089,
          precipitation: 1.2,
          pressure_msl: 1010.4,
          sunshine: 0.0,
          temperature: 16.4,
          wind_direction: 254,
          wind_speed: 13.0,
          cloud_cover: 100,
          dew_point: 14.4,
          relative_humidity: null,
          visibility: 18800,
          wind_gust_direction: null,
          wind_gust_speed: 29.6,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-13T22:00:00+02:00',
          source_id: 4089,
          precipitation: 1.0,
          pressure_msl: 1011.0,
          sunshine: 0.0,
          temperature: 16.1,
          wind_direction: 248,
          wind_speed: 13.0,
          cloud_cover: 100,
          dew_point: 14.3,
          relative_humidity: null,
          visibility: 20400,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-13T23:00:00+02:00',
          source_id: 4089,
          precipitation: 1.0,
          pressure_msl: 1011.3,
          sunshine: 0.0,
          temperature: 15.8,
          wind_direction: 244,
          wind_speed: 11.1,
          cloud_cover: 99,
          dew_point: 14.1,
          relative_humidity: null,
          visibility: 21700,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-14T00:00:00+02:00',
          source_id: 4089,
          precipitation: 0.8,
          pressure_msl: 1011.5,
          sunshine: 0.0,
          temperature: 15.4,
          wind_direction: 251,
          wind_speed: 11.1,
          cloud_cover: 100,
          dew_point: 14.0,
          relative_humidity: null,
          visibility: 26000,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-14T01:00:00+02:00',
          source_id: 4089,
          precipitation: 0.8,
          pressure_msl: 1011.6,
          sunshine: 0.0,
          temperature: 15.2,
          wind_direction: 256,
          wind_speed: 9.3,
          cloud_cover: 100,
          dew_point: 13.9,
          relative_humidity: null,
          visibility: 25700,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-14T02:00:00+02:00',
          source_id: 4089,
          precipitation: 0.7,
          pressure_msl: 1011.7,
          sunshine: 0.0,
          temperature: 15.0,
          wind_direction: 256,
          wind_speed: 9.3,
          cloud_cover: 100,
          dew_point: 13.7,
          relative_humidity: null,
          visibility: 22700,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-14T03:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1011.6,
          sunshine: 0.0,
          temperature: 14.7,
          wind_direction: 248,
          wind_speed: 11.1,
          cloud_cover: 99,
          dew_point: 13.6,
          relative_humidity: null,
          visibility: 22000,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-14T04:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1011.5,
          sunshine: 0.0,
          temperature: 14.7,
          wind_direction: 244,
          wind_speed: 11.1,
          cloud_cover: 99,
          dew_point: 13.5,
          relative_humidity: null,
          visibility: 19900,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-14T05:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1011.5,
          sunshine: 0.0,
          temperature: 14.6,
          wind_direction: 244,
          wind_speed: 9.3,
          cloud_cover: 98,
          dew_point: 13.2,
          relative_humidity: null,
          visibility: 17200,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-14T06:00:00+02:00',
          source_id: 4089,
          precipitation: 0.8,
          pressure_msl: 1011.6,
          sunshine: 0.0,
          temperature: 14.5,
          wind_direction: 246,
          wind_speed: 9.3,
          cloud_cover: 98,
          dew_point: 13.3,
          relative_humidity: null,
          visibility: 19000,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-14T07:00:00+02:00',
          source_id: 4089,
          precipitation: 1.1,
          pressure_msl: 1011.7,
          sunshine: 0.0,
          temperature: 14.6,
          wind_direction: 246,
          wind_speed: 9.3,
          cloud_cover: 99,
          dew_point: 13.3,
          relative_humidity: null,
          visibility: 18100,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-14T08:00:00+02:00',
          source_id: 4089,
          precipitation: 0.9,
          pressure_msl: 1012.1,
          sunshine: 0.0,
          temperature: 14.8,
          wind_direction: 245,
          wind_speed: 11.1,
          cloud_cover: 99,
          dew_point: 13.1,
          relative_humidity: null,
          visibility: 17900,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-14T09:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1012.0,
          sunshine: 0.0,
          temperature: 14.8,
          wind_direction: 250,
          wind_speed: 11.1,
          cloud_cover: 99,
          dew_point: 13.1,
          relative_humidity: null,
          visibility: 19400,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-14T10:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1012.1,
          sunshine: 0.0,
          temperature: 15.3,
          wind_direction: 250,
          wind_speed: 11.1,
          cloud_cover: 100,
          dew_point: 12.9,
          relative_humidity: null,
          visibility: 24900,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-14T11:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1012.2,
          sunshine: 0.0,
          temperature: 15.9,
          wind_direction: 256,
          wind_speed: 13.0,
          cloud_cover: 100,
          dew_point: 12.7,
          relative_humidity: null,
          visibility: 24800,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-14T12:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1012.3,
          sunshine: 0.0,
          temperature: 16.5,
          wind_direction: 261,
          wind_speed: 13.0,
          cloud_cover: 100,
          dew_point: 12.5,
          relative_humidity: null,
          visibility: 25100,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-14T13:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1012.4,
          sunshine: 1.0,
          temperature: 17.1,
          wind_direction: 246,
          wind_speed: 13.0,
          cloud_cover: 100,
          dew_point: 12.3,
          relative_humidity: null,
          visibility: 30000,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-14T14:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1012.5,
          sunshine: 2.0,
          temperature: 17.7,
          wind_direction: 257,
          wind_speed: 13.0,
          cloud_cover: 100,
          dew_point: 12.4,
          relative_humidity: null,
          visibility: 28400,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-14T15:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1012.3,
          sunshine: 5.0,
          temperature: 18.5,
          wind_direction: 254,
          wind_speed: 13.0,
          cloud_cover: 99,
          dew_point: 12.5,
          relative_humidity: null,
          visibility: 28300,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-14T16:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1012.3,
          sunshine: 8.0,
          temperature: 19.0,
          wind_direction: 246,
          wind_speed: 13.0,
          cloud_cover: 98,
          dew_point: 12.5,
          relative_humidity: null,
          visibility: 30600,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-14T17:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1012.1,
          sunshine: 8.0,
          temperature: 19.1,
          wind_direction: 244,
          wind_speed: 13.0,
          cloud_cover: 97,
          dew_point: 12.7,
          relative_humidity: null,
          visibility: 35100,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-14T18:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1012.0,
          sunshine: 8.0,
          temperature: 18.8,
          wind_direction: 242,
          wind_speed: 13.0,
          cloud_cover: 95,
          dew_point: 12.7,
          relative_humidity: null,
          visibility: 34000,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-14T19:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1012.2,
          sunshine: 8.0,
          temperature: 18.5,
          wind_direction: 239,
          wind_speed: 11.1,
          cloud_cover: 95,
          dew_point: 12.8,
          relative_humidity: null,
          visibility: 34000,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-14T20:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1012.6,
          sunshine: 7.0,
          temperature: 17.8,
          wind_direction: 229,
          wind_speed: 11.1,
          cloud_cover: 94,
          dew_point: 12.5,
          relative_humidity: null,
          visibility: 34800,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-14T21:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1013.0,
          sunshine: 5.0,
          temperature: 17.0,
          wind_direction: 219,
          wind_speed: 11.1,
          cloud_cover: 94,
          dew_point: 12.7,
          relative_humidity: null,
          visibility: 34300,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-14T22:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1013.2,
          sunshine: 2.0,
          temperature: 16.5,
          wind_direction: 215,
          wind_speed: 9.3,
          cloud_cover: 93,
          dew_point: 12.6,
          relative_humidity: null,
          visibility: 37700,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-14T23:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1013.4,
          sunshine: 0.0,
          temperature: 15.8,
          wind_direction: 207,
          wind_speed: 9.3,
          cloud_cover: 94,
          dew_point: 12.5,
          relative_humidity: null,
          visibility: 40800,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-15T00:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1013.7,
          sunshine: 0.0,
          temperature: 15.4,
          wind_direction: 209,
          wind_speed: 9.3,
          cloud_cover: 95,
          dew_point: 12.3,
          relative_humidity: null,
          visibility: 32400,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-15T01:00:00+02:00',
          source_id: 4089,
          precipitation: 0.2,
          pressure_msl: 1013.6,
          sunshine: 0.0,
          temperature: 15.0,
          wind_direction: 207,
          wind_speed: 9.3,
          cloud_cover: 95,
          dew_point: 12.3,
          relative_humidity: null,
          visibility: 29400,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-15T02:00:00+02:00',
          source_id: 4089,
          precipitation: 0.1,
          pressure_msl: 1013.4,
          sunshine: 0.0,
          temperature: 14.8,
          wind_direction: 196,
          wind_speed: 9.3,
          cloud_cover: 95,
          dew_point: 12.2,
          relative_humidity: null,
          visibility: 28100,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-15T03:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1012.9,
          sunshine: 0.0,
          temperature: 14.6,
          wind_direction: 194,
          wind_speed: 9.3,
          cloud_cover: 97,
          dew_point: 12.2,
          relative_humidity: null,
          visibility: 28200,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-15T04:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1012.8,
          sunshine: 0.0,
          temperature: 14.4,
          wind_direction: 194,
          wind_speed: 9.3,
          cloud_cover: 97,
          dew_point: 12.1,
          relative_humidity: null,
          visibility: 29900,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-15T05:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1012.7,
          sunshine: 0.0,
          temperature: 14.4,
          wind_direction: 189,
          wind_speed: 9.3,
          cloud_cover: 97,
          dew_point: 12.1,
          relative_humidity: null,
          visibility: 31500,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-15T06:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1012.5,
          sunshine: 1.0,
          temperature: 14.4,
          wind_direction: 181,
          wind_speed: 9.3,
          cloud_cover: 99,
          dew_point: 12.0,
          relative_humidity: null,
          visibility: 29700,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-15T07:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1012.3,
          sunshine: 2.0,
          temperature: 14.8,
          wind_direction: 182,
          wind_speed: 9.3,
          cloud_cover: 99,
          dew_point: 12.1,
          relative_humidity: null,
          visibility: 28000,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-15T08:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1012.2,
          sunshine: 2.0,
          temperature: 15.3,
          wind_direction: 181,
          wind_speed: 9.3,
          cloud_cover: 100,
          dew_point: 12.3,
          relative_humidity: null,
          visibility: 28600,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-15T09:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1012.3,
          sunshine: 2.0,
          temperature: 16.1,
          wind_direction: 194,
          wind_speed: 11.1,
          cloud_cover: 100,
          dew_point: 12.2,
          relative_humidity: null,
          visibility: 31600,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-15T10:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1012.2,
          sunshine: 1.0,
          temperature: 17.2,
          wind_direction: 176,
          wind_speed: 11.1,
          cloud_cover: 100,
          dew_point: 12.5,
          relative_humidity: null,
          visibility: 30100,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-15T11:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1012.4,
          sunshine: 3.0,
          temperature: 18.1,
          wind_direction: 181,
          wind_speed: 11.1,
          cloud_cover: 100,
          dew_point: 12.9,
          relative_humidity: null,
          visibility: 29100,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-15T12:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1012.1,
          sunshine: 4.0,
          temperature: 18.6,
          wind_direction: 190,
          wind_speed: 11.1,
          cloud_cover: 100,
          dew_point: 12.8,
          relative_humidity: null,
          visibility: 31500,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-15T13:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1012.2,
          sunshine: 7.0,
          temperature: 18.1,
          wind_direction: 188,
          wind_speed: 11.1,
          cloud_cover: 100,
          dew_point: 12.8,
          relative_humidity: null,
          visibility: 34400,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-15T14:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1011.7,
          sunshine: 8.0,
          temperature: 18.3,
          wind_direction: 195,
          wind_speed: 13.0,
          cloud_cover: 99,
          dew_point: 12.9,
          relative_humidity: null,
          visibility: 34200,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-15T15:00:00+02:00',
          source_id: 4089,
          precipitation: 0.7,
          pressure_msl: 1012.1,
          sunshine: 8.0,
          temperature: 18.8,
          wind_direction: 201,
          wind_speed: 11.1,
          cloud_cover: 99,
          dew_point: 13.1,
          relative_humidity: null,
          visibility: 39800,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-15T16:00:00+02:00',
          source_id: 4089,
          precipitation: 0.9,
          pressure_msl: 1012.0,
          sunshine: 8.0,
          temperature: 18.9,
          wind_direction: 184,
          wind_speed: 11.1,
          cloud_cover: 99,
          dew_point: 13.6,
          relative_humidity: null,
          visibility: 34400,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-15T17:00:00+02:00',
          source_id: 4089,
          precipitation: 1.4,
          pressure_msl: 1012.0,
          sunshine: 5.0,
          temperature: 18.8,
          wind_direction: 218,
          wind_speed: 11.1,
          cloud_cover: 99,
          dew_point: 13.7,
          relative_humidity: null,
          visibility: 32900,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-15T18:00:00+02:00',
          source_id: 4089,
          precipitation: 0.9,
          pressure_msl: 1011.9,
          sunshine: 9.0,
          temperature: 18.5,
          wind_direction: 197,
          wind_speed: 11.1,
          cloud_cover: 98,
          dew_point: 13.8,
          relative_humidity: null,
          visibility: 33200,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-15T19:00:00+02:00',
          source_id: 4089,
          precipitation: 1.3,
          pressure_msl: 1012.2,
          sunshine: 9.0,
          temperature: 18.1,
          wind_direction: 195,
          wind_speed: 9.3,
          cloud_cover: 98,
          dew_point: 14.1,
          relative_humidity: null,
          visibility: 28300,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-15T20:00:00+02:00',
          source_id: 4089,
          precipitation: 1.3,
          pressure_msl: 1012.5,
          sunshine: 5.0,
          temperature: 17.7,
          wind_direction: 189,
          wind_speed: 9.3,
          cloud_cover: 98,
          dew_point: 14.2,
          relative_humidity: null,
          visibility: 25400,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-15T21:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1012.9,
          sunshine: 4.0,
          temperature: 17.2,
          wind_direction: 200,
          wind_speed: 9.3,
          cloud_cover: 98,
          dew_point: 14.4,
          relative_humidity: null,
          visibility: 26500,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-15T22:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1013.3,
          sunshine: 2.0,
          temperature: 16.8,
          wind_direction: 197,
          wind_speed: 9.3,
          cloud_cover: 96,
          dew_point: 14.2,
          relative_humidity: null,
          visibility: 25600,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-15T23:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1013.9,
          sunshine: 0.0,
          temperature: 16.4,
          wind_direction: 204,
          wind_speed: 7.4,
          cloud_cover: 95,
          dew_point: 14.2,
          relative_humidity: null,
          visibility: 29200,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-16T00:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1014.1,
          sunshine: 0.0,
          temperature: 16.0,
          wind_direction: 202,
          wind_speed: 7.4,
          cloud_cover: 95,
          dew_point: 14.2,
          relative_humidity: null,
          visibility: 28400,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-16T01:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1014.5,
          sunshine: 0.0,
          temperature: 15.6,
          wind_direction: 209,
          wind_speed: 7.4,
          cloud_cover: 94,
          dew_point: 14.1,
          relative_humidity: null,
          visibility: 27500,
          wind_gust_direction: null,
          wind_gust_speed: 13.0,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-16T02:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1014.7,
          sunshine: 0.0,
          temperature: 15.5,
          wind_direction: 223,
          wind_speed: 7.4,
          cloud_cover: 92,
          dew_point: 14.0,
          relative_humidity: null,
          visibility: 27000,
          wind_gust_direction: null,
          wind_gust_speed: 13.0,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-16T03:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1014.8,
          sunshine: 0.0,
          temperature: 15.2,
          wind_direction: 229,
          wind_speed: 7.4,
          cloud_cover: 91,
          dew_point: 13.9,
          relative_humidity: null,
          visibility: 20900,
          wind_gust_direction: null,
          wind_gust_speed: 13.0,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-16T04:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.1,
          sunshine: 0.0,
          temperature: 14.9,
          wind_direction: 225,
          wind_speed: 7.4,
          cloud_cover: 92,
          dew_point: 14.0,
          relative_humidity: null,
          visibility: 18500,
          wind_gust_direction: null,
          wind_gust_speed: 13.0,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-16T05:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.3,
          sunshine: 0.0,
          temperature: 14.8,
          wind_direction: 222,
          wind_speed: 7.4,
          cloud_cover: 90,
          dew_point: 13.9,
          relative_humidity: null,
          visibility: 17000,
          wind_gust_direction: null,
          wind_gust_speed: 13.0,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-16T06:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.3,
          sunshine: 3.0,
          temperature: 14.8,
          wind_direction: 234,
          wind_speed: 7.4,
          cloud_cover: 90,
          dew_point: 13.8,
          relative_humidity: null,
          visibility: 14700,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-16T07:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.7,
          sunshine: 8.0,
          temperature: 15.1,
          wind_direction: 240,
          wind_speed: 7.4,
          cloud_cover: 90,
          dew_point: 13.9,
          relative_humidity: null,
          visibility: 13800,
          wind_gust_direction: null,
          wind_gust_speed: 13.0,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-16T08:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1015.9,
          sunshine: 12.0,
          temperature: 15.7,
          wind_direction: 260,
          wind_speed: 7.4,
          cloud_cover: 90,
          dew_point: 13.9,
          relative_humidity: null,
          visibility: 13700,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-16T09:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.1,
          sunshine: 18.0,
          temperature: 16.7,
          wind_direction: 274,
          wind_speed: 7.4,
          cloud_cover: 89,
          dew_point: 14.0,
          relative_humidity: null,
          visibility: 15800,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-16T10:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.3,
          sunshine: 21.0,
          temperature: 17.8,
          wind_direction: 283,
          wind_speed: 7.4,
          cloud_cover: 87,
          dew_point: 14.1,
          relative_humidity: null,
          visibility: 16500,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-16T11:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.2,
          sunshine: 21.0,
          temperature: 19.1,
          wind_direction: 301,
          wind_speed: 9.3,
          cloud_cover: 88,
          dew_point: 13.8,
          relative_humidity: null,
          visibility: 19100,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-16T12:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.3,
          sunshine: 24.0,
          temperature: 19.9,
          wind_direction: 296,
          wind_speed: 9.3,
          cloud_cover: 87,
          dew_point: 13.7,
          relative_humidity: null,
          visibility: 21200,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-16T13:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1016.3,
          sunshine: 24.0,
          temperature: 20.9,
          wind_direction: 296,
          wind_speed: 9.3,
          cloud_cover: 87,
          dew_point: 13.6,
          relative_humidity: null,
          visibility: 24100,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-16T14:00:00+02:00',
          source_id: 4089,
          precipitation: 0.7,
          pressure_msl: 1016.1,
          sunshine: 20.0,
          temperature: 21.3,
          wind_direction: 321,
          wind_speed: 9.3,
          cloud_cover: 89,
          dew_point: 13.4,
          relative_humidity: null,
          visibility: 26000,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-16T15:00:00+02:00',
          source_id: 4089,
          precipitation: 0.2,
          pressure_msl: 1015.9,
          sunshine: 21.0,
          temperature: 21.8,
          wind_direction: 328,
          wind_speed: 9.3,
          cloud_cover: 90,
          dew_point: 13.4,
          relative_humidity: null,
          visibility: 27000,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-16T16:00:00+02:00',
          source_id: 4089,
          precipitation: 0.4,
          pressure_msl: 1015.8,
          sunshine: 20.0,
          temperature: 21.9,
          wind_direction: 314,
          wind_speed: 11.1,
          cloud_cover: 91,
          dew_point: 13.4,
          relative_humidity: null,
          visibility: 28200,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-16T17:00:00+02:00',
          source_id: 4089,
          precipitation: 0.7,
          pressure_msl: 1015.7,
          sunshine: 19.0,
          temperature: 21.9,
          wind_direction: 305,
          wind_speed: 9.3,
          cloud_cover: 92,
          dew_point: 13.4,
          relative_humidity: null,
          visibility: 30100,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-16T18:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1015.6,
          sunshine: 16.0,
          temperature: 21.7,
          wind_direction: 275,
          wind_speed: 9.3,
          cloud_cover: 93,
          dew_point: 13.6,
          relative_humidity: null,
          visibility: 32600,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-16T19:00:00+02:00',
          source_id: 4089,
          precipitation: 0.9,
          pressure_msl: 1015.7,
          sunshine: 14.0,
          temperature: 21.0,
          wind_direction: 260,
          wind_speed: 9.3,
          cloud_cover: 93,
          dew_point: 13.8,
          relative_humidity: null,
          visibility: 31900,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-16T20:00:00+02:00',
          source_id: 4089,
          precipitation: 0.9,
          pressure_msl: 1016.9,
          sunshine: 11.0,
          temperature: 19.9,
          wind_direction: 254,
          wind_speed: 9.3,
          cloud_cover: 95,
          dew_point: 13.9,
          relative_humidity: null,
          visibility: 21900,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-16T21:00:00+02:00',
          source_id: 4089,
          precipitation: 1.0,
          pressure_msl: 1017.3,
          sunshine: 6.0,
          temperature: 19.3,
          wind_direction: 243,
          wind_speed: 9.3,
          cloud_cover: 95,
          dew_point: 14.2,
          relative_humidity: null,
          visibility: 21800,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-16T22:00:00+02:00',
          source_id: 4089,
          precipitation: 1.0,
          pressure_msl: 1017.7,
          sunshine: 2.0,
          temperature: 18.1,
          wind_direction: 250,
          wind_speed: 9.3,
          cloud_cover: 94,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 25700,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-16T23:00:00+02:00',
          source_id: 4089,
          precipitation: 1.0,
          pressure_msl: 1018.2,
          sunshine: 0.0,
          temperature: 17.6,
          wind_direction: 251,
          wind_speed: 9.3,
          cloud_cover: 93,
          dew_point: 14.8,
          relative_humidity: null,
          visibility: 22200,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-17T00:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1018.5,
          sunshine: 0.0,
          temperature: 17.1,
          wind_direction: 253,
          wind_speed: 9.3,
          cloud_cover: 93,
          dew_point: 14.8,
          relative_humidity: null,
          visibility: 22600,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-17T01:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1018.5,
          sunshine: 0.0,
          temperature: 16.6,
          wind_direction: 253,
          wind_speed: 7.4,
          cloud_cover: 92,
          dew_point: 14.8,
          relative_humidity: null,
          visibility: 22600,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-17T02:00:00+02:00',
          source_id: 4089,
          precipitation: 0.3,
          pressure_msl: 1018.6,
          sunshine: 0.0,
          temperature: 16.1,
          wind_direction: 260,
          wind_speed: 9.3,
          cloud_cover: 91,
          dew_point: 14.7,
          relative_humidity: null,
          visibility: 20400,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-17T03:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1018.5,
          sunshine: 0.0,
          temperature: 15.9,
          wind_direction: 265,
          wind_speed: 9.3,
          cloud_cover: 88,
          dew_point: 14.7,
          relative_humidity: null,
          visibility: 18600,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-17T04:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1018.3,
          sunshine: 0.0,
          temperature: 15.7,
          wind_direction: 268,
          wind_speed: 7.4,
          cloud_cover: 85,
          dew_point: 14.5,
          relative_humidity: null,
          visibility: 13500,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-17T05:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1018.7,
          sunshine: 0.0,
          temperature: 15.5,
          wind_direction: 267,
          wind_speed: 7.4,
          cloud_cover: 82,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 12200,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-17T06:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1018.7,
          sunshine: 2.0,
          temperature: 15.6,
          wind_direction: 272,
          wind_speed: 7.4,
          cloud_cover: 80,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 12200,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-17T07:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1018.7,
          sunshine: 6.0,
          temperature: 16.1,
          wind_direction: 275,
          wind_speed: 9.3,
          cloud_cover: 78,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 12000,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-17T08:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1019.1,
          sunshine: 14.0,
          temperature: 16.6,
          wind_direction: 276,
          wind_speed: 9.3,
          cloud_cover: 78,
          dew_point: 14.5,
          relative_humidity: null,
          visibility: 10600,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-17T09:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1018.6,
          sunshine: 14.0,
          temperature: 17.5,
          wind_direction: 279,
          wind_speed: 9.3,
          cloud_cover: 77,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 12100,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-17T10:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1018.7,
          sunshine: 16.0,
          temperature: 18.6,
          wind_direction: 281,
          wind_speed: 9.3,
          cloud_cover: 78,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 15100,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-17T11:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1018.6,
          sunshine: 17.0,
          temperature: 19.7,
          wind_direction: 283,
          wind_speed: 9.3,
          cloud_cover: 80,
          dew_point: 14.4,
          relative_humidity: null,
          visibility: 14800,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-17T12:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.9,
          sunshine: 20.0,
          temperature: 20.6,
          wind_direction: 294,
          wind_speed: 11.1,
          cloud_cover: 78,
          dew_point: 14.4,
          relative_humidity: null,
          visibility: 19100,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-17T13:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.9,
          sunshine: 21.0,
          temperature: 21.5,
          wind_direction: 300,
          wind_speed: 11.1,
          cloud_cover: 77,
          dew_point: 14.3,
          relative_humidity: null,
          visibility: 21800,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-17T14:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.5,
          sunshine: 21.0,
          temperature: 22.0,
          wind_direction: 313,
          wind_speed: 11.1,
          cloud_cover: 77,
          dew_point: 14.2,
          relative_humidity: null,
          visibility: 26100,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-17T15:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.1,
          sunshine: 22.0,
          temperature: 22.2,
          wind_direction: 322,
          wind_speed: 11.1,
          cloud_cover: 75,
          dew_point: 14.0,
          relative_humidity: null,
          visibility: 28100,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-17T16:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.6,
          sunshine: 22.0,
          temperature: 22.4,
          wind_direction: 332,
          wind_speed: 11.1,
          cloud_cover: 74,
          dew_point: 14.1,
          relative_humidity: null,
          visibility: 27900,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-17T17:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.4,
          sunshine: 22.0,
          temperature: 22.4,
          wind_direction: 326,
          wind_speed: 11.1,
          cloud_cover: 72,
          dew_point: 14.1,
          relative_humidity: null,
          visibility: 27600,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-17T18:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.3,
          sunshine: 21.0,
          temperature: 22.4,
          wind_direction: 312,
          wind_speed: 11.1,
          cloud_cover: 72,
          dew_point: 14.3,
          relative_humidity: null,
          visibility: 27200,
          wind_gust_direction: null,
          wind_gust_speed: 24.1,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-17T19:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.3,
          sunshine: 20.0,
          temperature: 22.1,
          wind_direction: 304,
          wind_speed: 11.1,
          cloud_cover: 71,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 27100,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-17T20:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.9,
          sunshine: 16.0,
          temperature: 21.4,
          wind_direction: 298,
          wind_speed: 9.3,
          cloud_cover: 71,
          dew_point: 14.7,
          relative_humidity: null,
          visibility: 24000,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-17T21:00:00+02:00',
          source_id: 4089,
          precipitation: 0.9,
          pressure_msl: 1017.0,
          sunshine: 10.0,
          temperature: 20.4,
          wind_direction: 261,
          wind_speed: 9.3,
          cloud_cover: 75,
          dew_point: 15.1,
          relative_humidity: null,
          visibility: 26100,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-17T22:00:00+02:00',
          source_id: 4089,
          precipitation: 1.8,
          pressure_msl: 1017.5,
          sunshine: 0.0,
          temperature: 19.5,
          wind_direction: 266,
          wind_speed: 9.3,
          cloud_cover: 72,
          dew_point: 15.2,
          relative_humidity: null,
          visibility: 22100,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-17T23:00:00+02:00',
          source_id: 4089,
          precipitation: 1.8,
          pressure_msl: 1018.0,
          sunshine: 0.0,
          temperature: 18.7,
          wind_direction: 252,
          wind_speed: 7.4,
          cloud_cover: 74,
          dew_point: 15.4,
          relative_humidity: null,
          visibility: 26100,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-18T00:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.8,
          sunshine: 0.0,
          temperature: 18.1,
          wind_direction: 255,
          wind_speed: 7.4,
          cloud_cover: 76,
          dew_point: 15.4,
          relative_humidity: null,
          visibility: 18200,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-18T01:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.7,
          sunshine: 0.0,
          temperature: 17.6,
          wind_direction: 258,
          wind_speed: 7.4,
          cloud_cover: 77,
          dew_point: 15.2,
          relative_humidity: null,
          visibility: 18500,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-18T02:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1018.3,
          sunshine: 0.0,
          temperature: 17.3,
          wind_direction: 260,
          wind_speed: 7.4,
          cloud_cover: 81,
          dew_point: 15.1,
          relative_humidity: null,
          visibility: 24200,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-18T03:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1018.0,
          sunshine: 0.0,
          temperature: 16.9,
          wind_direction: 253,
          wind_speed: 9.3,
          cloud_cover: 82,
          dew_point: 15.0,
          relative_humidity: null,
          visibility: 21600,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-18T04:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.8,
          sunshine: 0.0,
          temperature: 16.7,
          wind_direction: 256,
          wind_speed: 9.3,
          cloud_cover: 80,
          dew_point: 14.9,
          relative_humidity: null,
          visibility: 17700,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-18T05:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.9,
          sunshine: 0.0,
          temperature: 16.4,
          wind_direction: 251,
          wind_speed: 7.4,
          cloud_cover: 80,
          dew_point: 15.0,
          relative_humidity: null,
          visibility: 15200,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-18T06:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1018.1,
          sunshine: 4.0,
          temperature: 16.5,
          wind_direction: 256,
          wind_speed: 7.4,
          cloud_cover: 79,
          dew_point: 14.9,
          relative_humidity: null,
          visibility: 12500,
          wind_gust_direction: null,
          wind_gust_speed: 14.8,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-18T07:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.6,
          sunshine: 8.0,
          temperature: 17.0,
          wind_direction: 258,
          wind_speed: 7.4,
          cloud_cover: 80,
          dew_point: 15.0,
          relative_humidity: null,
          visibility: 12200,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'cloudy',
        },
        {
          timestamp: '2021-07-18T08:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.8,
          sunshine: 16.0,
          temperature: 17.6,
          wind_direction: 270,
          wind_speed: 9.3,
          cloud_cover: 77,
          dew_point: 15.1,
          relative_humidity: null,
          visibility: 13600,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-18T09:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.6,
          sunshine: 20.0,
          temperature: 18.6,
          wind_direction: 289,
          wind_speed: 9.3,
          cloud_cover: 77,
          dew_point: 15.0,
          relative_humidity: null,
          visibility: 14800,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-18T10:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.3,
          sunshine: 19.0,
          temperature: 19.6,
          wind_direction: 293,
          wind_speed: 9.3,
          cloud_cover: 79,
          dew_point: 15.0,
          relative_humidity: null,
          visibility: 15300,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-18T11:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1017.2,
          sunshine: 20.0,
          temperature: 20.4,
          wind_direction: 307,
          wind_speed: 11.1,
          cloud_cover: 79,
          dew_point: 15.0,
          relative_humidity: null,
          visibility: 16700,
          wind_gust_direction: null,
          wind_gust_speed: 20.4,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-18T12:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.5,
          sunshine: 21.0,
          temperature: 21.3,
          wind_direction: 325,
          wind_speed: 11.1,
          cloud_cover: 74,
          dew_point: 14.8,
          relative_humidity: null,
          visibility: 19200,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-18T13:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.4,
          sunshine: 23.0,
          temperature: 21.9,
          wind_direction: 335,
          wind_speed: 11.1,
          cloud_cover: 72,
          dew_point: 14.6,
          relative_humidity: null,
          visibility: 21200,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-18T14:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.5,
          sunshine: 24.0,
          temperature: 22.7,
          wind_direction: 343,
          wind_speed: 13.0,
          cloud_cover: 73,
          dew_point: 14.5,
          relative_humidity: null,
          visibility: 25600,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'dry',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-18T15:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1016.0,
          sunshine: 26.0,
          temperature: 22.8,
          wind_direction: 351,
          wind_speed: 13.0,
          cloud_cover: 72,
          dew_point: 14.5,
          relative_humidity: null,
          visibility: 28500,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-18T16:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1015.6,
          sunshine: 28.0,
          temperature: 23.0,
          wind_direction: 358,
          wind_speed: 13.0,
          cloud_cover: 72,
          dew_point: 14.4,
          relative_humidity: null,
          visibility: 24700,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-18T17:00:00+02:00',
          source_id: 4089,
          precipitation: 0.5,
          pressure_msl: 1015.3,
          sunshine: 26.0,
          temperature: 22.9,
          wind_direction: 353,
          wind_speed: 13.0,
          cloud_cover: 71,
          dew_point: 14.4,
          relative_humidity: null,
          visibility: 22800,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-18T18:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1014.9,
          sunshine: 25.0,
          temperature: 22.7,
          wind_direction: 351,
          wind_speed: 13.0,
          cloud_cover: 66,
          dew_point: 14.2,
          relative_humidity: null,
          visibility: 24700,
          wind_gust_direction: null,
          wind_gust_speed: 27.8,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-18T19:00:00+02:00',
          source_id: 4089,
          precipitation: 0.8,
          pressure_msl: 1015.2,
          sunshine: 26.0,
          temperature: 22.2,
          wind_direction: 341,
          wind_speed: 11.1,
          cloud_cover: 58,
          dew_point: 14.4,
          relative_humidity: null,
          visibility: 25400,
          wind_gust_direction: null,
          wind_gust_speed: 25.9,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-18T20:00:00+02:00',
          source_id: 4089,
          precipitation: 0.6,
          pressure_msl: 1015.7,
          sunshine: 22.0,
          temperature: 21.6,
          wind_direction: 342,
          wind_speed: 9.3,
          cloud_cover: 64,
          dew_point: 14.7,
          relative_humidity: null,
          visibility: 25700,
          wind_gust_direction: null,
          wind_gust_speed: 22.2,
          condition: 'rain',
          icon: 'rain',
        },
        {
          timestamp: '2021-07-18T21:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.0,
          sunshine: 13.0,
          temperature: 20.4,
          wind_direction: 328,
          wind_speed: 9.3,
          cloud_cover: 66,
          dew_point: 14.9,
          relative_humidity: null,
          visibility: 28800,
          wind_gust_direction: null,
          wind_gust_speed: 18.5,
          condition: 'rain',
          icon: 'partly-cloudy-day',
        },
        {
          timestamp: '2021-07-18T22:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.4,
          sunshine: 0.0,
          temperature: 19.6,
          wind_direction: 309,
          wind_speed: 7.4,
          cloud_cover: 67,
          dew_point: 15.0,
          relative_humidity: null,
          visibility: 23700,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'rain',
          icon: 'partly-cloudy-night',
        },
        {
          timestamp: '2021-07-18T23:00:00+02:00',
          source_id: 4089,
          precipitation: 0.0,
          pressure_msl: 1016.8,
          sunshine: 0.0,
          temperature: 18.5,
          wind_direction: 304,
          wind_speed: 7.4,
          cloud_cover: 68,
          dew_point: 15.1,
          relative_humidity: null,
          visibility: 21200,
          wind_gust_direction: null,
          wind_gust_speed: 16.7,
          condition: 'dry',
          icon: 'partly-cloudy-night',
        },
      ],
      sources: [
        {
          id: 46586,
          dwd_station_id: '03379',
          observation_type: 'historical',
          lat: 48.1632,
          lon: 11.5429,
          height: 515.37,
          station_name: 'München-Stadt',
          wmo_station_id: '10865',
          first_record: '2010-01-01T00:00:00+00:00',
          last_record: '2021-07-11T23:00:00+00:00',
          distance: 3777.0,
        },
        {
          id: 6269,
          dwd_station_id: '03379',
          observation_type: 'current',
          lat: 48.13,
          lon: 11.55,
          height: 520.0,
          station_name: 'MUENCHEN STADT',
          wmo_station_id: '10865',
          first_record: '2021-07-10T16:00:00+00:00',
          last_record: '2021-07-12T15:00:00+00:00',
          distance: 2491.0,
        },
        {
          id: 4089,
          dwd_station_id: '03379',
          observation_type: 'forecast',
          lat: 48.13,
          lon: 11.55,
          height: 520.0,
          station_name: 'MUENCHEN STADT',
          wmo_station_id: '10865',
          first_record: '2021-07-12T13:00:00+00:00',
          last_record: '2021-07-22T15:00:00+00:00',
          distance: 2491.0,
        },
      ],
    } as RawDayWeatherDataType

    const processedWeatherData = this.processWeatherData(
      tempWeatherData,
      48.136,
      11.577
    )

    return new Promise<typeof processedWeatherData>(resolve =>
      setTimeout(() => {
        resolve(processedWeatherData)
      }, DUMMY_DELAY + 200)
    )
  }

  static processCurrentWeatherData(
    weatherData: RawCurrentWeatherDataType
  ): WeatherDataType {
    const weather = weatherData.weather
    return {
      timestamp: weather.timestamp,
      cloudCover: weather.cloud_cover,
      condition: weather.condition,
      dewPoint: weather.dew_point,
      precipitation: weather.precipitation_60,
      pressureMsl: weather.pressure_msl,
      relativeHumidity: weather.relative_humidity,
      visibility: weather.visibility,
      windDirection: weather.wind_direction_10,
      windSpeed: weather.wind_speed_10,
      windGustDirection: weather.wind_gust_direction_10,
      windGustSpeed: weather.wind_gust_speed_10,
      sunshine: weather.sunshine_30,
      temperature: Math.round(weather.temperature),
      icon: weather.icon,
    }
  }

  static processWeatherData(
    weatherData: RawDayWeatherDataType,
    lat,
    lon
  ): any[] {
    const mapped = weatherData.weather.map(weather => ({
      timestamp: weather.timestamp,
      cloudCover: weather.cloud_cover,
      condition: weather.condition,
      dewPoint: weather.dew_point,
      precipitation: weather.precipitation,
      pressureMsl: weather.pressure_msl,
      relativeHumidity: weather.relative_humidity,
      visibility: weather.visibility,
      windDirection: weather.wind_direction,
      windSpeed: weather.wind_speed,
      windGustDirection: weather.wind_gust_direction,
      windGustSpeed: weather.wind_gust_speed,
      sunshine: weather.sunshine,
      temperature: Math.round(weather.temperature),
      icon: weather.icon,
    }))

    const daysHash = {}
    mapped.forEach(element => {
      const day = element.timestamp.split('T')[0]
      if (!daysHash[day]) {
        daysHash[day] = []
      }
      daysHash[day].push(element)
    })

    let iconCount = {}
    const between = (val: number, left: number, right: number) =>
      val >= left && val <= right
    const getHours = (timestamp: string | number | Date) =>
      new Date(timestamp).getHours()
    const mostRelevantIcon = times => {
      const iconValue = (icon: WeatherIconType) => {
        switch (icon) {
          case 'thunderstorm':
          case 'hail':
            return 12
          default:
            return 1
        }
      }
      iconCount = {}
      times.forEach(
        element =>
          (iconCount[element.icon] =
            iconValue(element.icon) + (iconCount[element.icon] ?? 0))
      )
      return Object.entries(iconCount).reduce(
        (acc, [key, value]) => (value > acc[1] ? [key, value] : acc),
        ['clear-day', 0]
      )[0] as WeatherIconType
    }

    const getIconColor = (icon: WeatherIconType) => {
      switch (icon) {
        case 'rain':
        case 'sleet':
        case 'hail':
        case 'snow':
        case 'thunderstorm':
          return '#0066ED'
        case 'clear-day':
        case 'clear-night':
        case 'partly-cloudy-day':
        case 'partly-cloudy-night':
          return '#FFB901'
        default:
          return '#444444'
      }
    }

    const dayGraphData = (times: WeatherDataType[]) => {
      let max = -Infinity,
        min = Infinity

      times.forEach(element => {
        if (element.temperature > max) max = element.temperature
        if (element.temperature < min) min = element.temperature
      })
      return {
        min: { temperature: min },
        max: { temperature: max },
        dayGraph: times.map(time => {
          return {
            timestamp: time.timestamp,
            temperature: Math.abs(
              (time.temperature - min) / (Math.abs(max) - Math.abs(min))
            ),
            precipitation:
              Math.min(Math.pow(Math.sqrt(time.precipitation) * 1.7, 2), 6) / 6,
            sunniness: 1 - time.cloudCover / 100,
          }
        }),
      }
    }
    const result = Object.entries(daysHash).map(
      ([key, value]: [string, (WeatherDataType & { hours?: number })[]]) => {
        value = value.map(v => ({
          ...v,
          hours: getHours(v.timestamp),
        }))

        const day = new Date(key)
        const dayTimes = []
        const morningTimes = []
        const noonTimes = []
        const eveningTimes = []
        const dayLight = getSunriseSunset(day, lat, lon)

        value.forEach(v => {
          if (between(v.hours, 5, 22)) dayTimes.push(v)
          if (between(v.hours, 4, 9)) morningTimes.push(v)
          if (between(v.hours, 10, 17)) noonTimes.push(v)
          if (between(v.hours, 18, 22)) eveningTimes.push(v)
        })

        return {
          day,
          dayLight,
          dayParts: [morningTimes, noonTimes, eveningTimes].map(t => {
            const icon = mostRelevantIcon(t)
            return { icon, color: getIconColor(icon) }
          }),
          ...dayGraphData(dayTimes),
          data: value as WeatherDataType[],
        }
      }
    )

    return result
  }
}
